/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Root;

import Janelas.HistoricoGlobal;
import Janelas.AdmAcoes;
import Janelas.Equipamentos;
import Janelas.HistóricoAD;
import Modos.Administração.TodaFolhasSalariais;
import Modos.Administração.TodasFolhasDespesas;
import Objetos.TemaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Custodio Quingumba
 */
public class Gerenciar extends javax.swing.JFrame {

    private String previlegio, usuario;
    private int idUsuario, idTema;
    private Color CorBotao, CorLetra, CorFundo;

    public void SetCorBotoes(Color fundo, Color letra) {
        //COR DO FUNDO DO BOTAO

        btClientes.setBackground(fundo);
        btnFolha.setBackground(fundo);
        btHistorico.setBackground(fundo);
        btHistoricoGeral.setBackground(fundo);
        btStoque.setBackground(fundo);
        btDespesa.setBackground(fundo);

        //COR A LETRA
        btClientes.setForeground(letra);
        btDespesa.setForeground(letra);
        btnFolha.setForeground(letra);
        btHistoricoGeral.setForeground(letra);
        btHistorico.setForeground(letra);
        btStoque.setForeground(letra);
    }

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
    }

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public void setPrevilegio(String previlegio) {
        this.previlegio = previlegio;
    }

    public String getPrevilegio() {
        return previlegio;
    }

    /**
     * Creates new form ClientesOuEquipamento
     */
    public Gerenciar() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        btClientes = new javax.swing.JButton();
        btStoque = new javax.swing.JButton();
        btHistorico = new javax.swing.JButton();
        btHistoricoGeral = new javax.swing.JButton();
        btnFolha = new javax.swing.JButton();
        btDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIAR");
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btClientes.setBackground(new java.awt.Color(241, 241, 241));
        btClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btClientes.setForeground(new java.awt.Color(204, 0, 204));
        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/adicionar-cliente.png"))); // NOI18N
        btClientes.setText("CLIENTES");
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        pFundo.add(btClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        btStoque.setBackground(new java.awt.Color(241, 241, 241));
        btStoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btStoque.setForeground(new java.awt.Color(204, 0, 204));
        btStoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inventario.png"))); // NOI18N
        btStoque.setText("STOQUE");
        btStoque.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btStoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStoqueActionPerformed(evt);
            }
        });
        pFundo.add(btStoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 50));

        btHistorico.setBackground(new java.awt.Color(241, 241, 241));
        btHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHistorico.setForeground(new java.awt.Color(204, 0, 204));
        btHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/historia.png"))); // NOI18N
        btHistorico.setText("HISTÓRICO");
        btHistorico.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoActionPerformed(evt);
            }
        });
        pFundo.add(btHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 160, 50));

        btHistoricoGeral.setBackground(new java.awt.Color(241, 241, 241));
        btHistoricoGeral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHistoricoGeral.setForeground(new java.awt.Color(204, 0, 204));
        btHistoricoGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/historia.png"))); // NOI18N
        btHistoricoGeral.setText("HISTÓRICO GERAL");
        btHistoricoGeral.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btHistoricoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoGeralActionPerformed(evt);
            }
        });
        pFundo.add(btHistoricoGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 180, 50));

        btnFolha.setBackground(new java.awt.Color(241, 241, 241));
        btnFolha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFolha.setForeground(new java.awt.Color(204, 0, 204));
        btnFolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inventario.png"))); // NOI18N
        btnFolha.setText("FOLHA SALARIAL");
        btnFolha.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFolha.setIconTextGap(20);
        btnFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFolhaActionPerformed(evt);
            }
        });
        pFundo.add(btnFolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 180, 50));

        btDespesa.setBackground(new java.awt.Color(241, 241, 241));
        btDespesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDespesa.setForeground(new java.awt.Color(204, 0, 204));
        btDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inventario.png"))); // NOI18N
        btDespesa.setText("DESPESAS");
        btDespesa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btDespesa.setIconTextGap(20);
        btDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDespesaActionPerformed(evt);
            }
        });
        pFundo.add(btDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 190, 50));

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        // TODO add your handling code here:
        AdmAcoes adm = new AdmAcoes();
        adm.setIdUsuario(getIdUsuario());
        adm.setIdTema(idTema);
        adm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btClientesActionPerformed

    private void btStoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStoqueActionPerformed
        // TODO add your handling code here:
        Equipamentos eq = new Equipamentos();
        eq.setIdUsuario(getIdUsuario());
        eq.setIdTema(idTema);
        eq.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btStoqueActionPerformed

    private void btHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoActionPerformed
        // TODO add your handling code here:
        HistóricoAD h = new HistóricoAD();
        h.setVisible(true);
        h.setIdTema(idTema);
        this.dispose();
    }//GEN-LAST:event_btHistoricoActionPerformed

    private void btHistoricoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoGeralActionPerformed
        // TODO add your handling code here:
        HistoricoGlobal h = new HistoricoGlobal();
        h.setVisible(true);
        h.setIdTema(idTema);
        this.dispose();
    }//GEN-LAST:event_btHistoricoGeralActionPerformed

    private void btnFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFolhaActionPerformed
        // TODO add your handling code here:
        TodaFolhasSalariais tdFolha = new TodaFolhasSalariais();
        tdFolha.setIdUsuario(idUsuario);
        tdFolha.setVisible(true);
        tdFolha.setIdTema(idTema);
        this.dispose();
    }//GEN-LAST:event_btnFolhaActionPerformed

    private void btDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDespesaActionPerformed
        // TODO add your handling code here:
        TodasFolhasDespesas tfd = new TodasFolhasDespesas();
        tfd.setIdUsuario(idUsuario);
        tfd.setPrevilegio2(previlegio);
        tfd.setIdTema(idTema);
        this.dispose();
        tfd.setVisible(true);
    }//GEN-LAST:event_btDespesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btDespesa;
    private javax.swing.JButton btHistorico;
    private javax.swing.JButton btHistoricoGeral;
    private javax.swing.JButton btStoque;
    private javax.swing.JButton btnFolha;
    private javax.swing.JPanel pFundo;
    // End of variables declaration//GEN-END:variables
}
