/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Tecnico;

import Janelas.AdmAcoes;
import Janelas.Clientes;
import Janelas.Login;
import Janelas.MeuPerfil;
import Janelas.Sobre;
import Objetos.Dados;
import Objetos.TemaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Custódio Quingumba
 */
public final class ModoTécnico extends javax.swing.JFrame {

    private String previlegio, usuario;
    private int idUsuario, idTema;
    private Color CorBotao, CorLetra, CorFundo;
    List<TemaOBJ> tema = new ArrayList<>();

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
        fundo = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
        lbUsuario.setText("Usuário: " + usuario);
    }

    public String getPrevilegio() {
        return previlegio;
    }

    public void setPrevilegio(String previlegio) {
        this.previlegio = previlegio;
        if (getPrevilegio().equalsIgnoreCase("f")) {
            lbPrevilegio.setText("Previlegio: Área Administrativa");
        }
        if (getPrevilegio().equalsIgnoreCase("t")) {
            lbPrevilegio.setText("Previlegio: Área Técnica");
        }
        if (getPrevilegio().equalsIgnoreCase("a")) {
            lbPrevilegio.setText("Previlegio: Administrador do Sistema - DOPE");
        }
    }

    /**
     * Creates new form AmbienteDeTrabalho
     */
    public ModoTécnico() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        tema = new Dados().temas();
        cbTemas.removeAllItems();
        for (TemaOBJ t : tema) {
            cbTemas.addItem(t.getNome());
        }
        pFundo.setBackground(new Color(0x303135));
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        idTema = cbTemas.getSelectedIndex();
        if (idTema == 0) {
            setCorBotao(new Color(0xf1f1f1));
            setCorLetra(new Color(0xcc00cc));
            setCorFundo(new Color(0xfbfbfc));
            SetCorBotoes(CorBotao, CorLetra);
        } else {
            setCorBotao(new Color(0x241f24));
            setCorLetra(new Color(0xcc00cc));
            setCorFundo(new Color(0x110e11));
            SetCorBotoes(CorBotao, CorLetra);
        }
    }

    void SetCorBotoes(Color fundo, Color letra) {
        //COR DO FUNDO DO BOTAO

        cbTemas.setBackground(fundo);
        btDesAct.setBackground(fundo);
        btExit.setBackground(fundo);
        btLogout.setBackground(fundo);
        btNovo.setBackground(fundo);
        btSobre.setBackground(fundo);
        btTodos.setBackground(fundo);
        btnCto.setBackground(fundo);

        //COR A LETRA
        cbTemas.setForeground(letra);
        btDesAct.setForeground(letra);
        btExit.setForeground(letra);
        btLogout.setForeground(letra);
        btNovo.setForeground(letra);
        btSobre.setForeground(letra);
        btTodos.setForeground(letra);
        btnCto.setForeground(letra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btTodos = new javax.swing.JButton();
        btDesAct = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btSobre = new javax.swing.JButton();
        btnCto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        lbPrevilegio = new javax.swing.JLabel();
        lbUsuario1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTemas = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALLCENTER - GERENCIADOR DE CLIENTES E PARCEIROS");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1193, 763));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setBackground(new java.awt.Color(255, 255, 255));
        pFundo.setOpaque(false);

        jPanel1.setForeground(new java.awt.Color(153, 0, 153));
        jPanel1.setOpaque(false);

        btNovo.setBackground(new java.awt.Color(241, 241, 241));
        btNovo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btNovo.setForeground(new java.awt.Color(204, 0, 204));
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/adicionar-ficheiro.png"))); // NOI18N
        btNovo.setText("NOVO");
        btNovo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btNovo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btNovo.setIconTextGap(40);
        btNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNovoMouseExited(evt);
            }
        });
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btTodos.setBackground(new java.awt.Color(241, 241, 241));
        btTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTodos.setForeground(new java.awt.Color(204, 0, 204));
        btTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/adicionar-cliente.png"))); // NOI18N
        btTodos.setText("CLIENTES");
        btTodos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btTodos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btTodos.setIconTextGap(15);
        btTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btTodosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btTodosMouseExited(evt);
            }
        });
        btTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodosActionPerformed(evt);
            }
        });

        btDesAct.setBackground(new java.awt.Color(241, 241, 241));
        btDesAct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btDesAct.setForeground(new java.awt.Color(204, 0, 204));
        btDesAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lista-de-controle.png"))); // NOI18N
        btDesAct.setText("ACTIVAR");
        btDesAct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btDesAct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btDesAct.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btDesAct.setIconTextGap(25);
        btDesAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDesActMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDesActMouseExited(evt);
            }
        });
        btDesAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesActActionPerformed(evt);
            }
        });

        btExit.setBackground(new java.awt.Color(241, 241, 241));
        btExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btExit.setForeground(new java.awt.Color(204, 0, 204));
        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/fechar.png"))); // NOI18N
        btExit.setText("SAIR");
        btExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btExit.setIconTextGap(50);
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btExitMouseExited(evt);
            }
        });
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(241, 241, 241));
        btLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLogout.setForeground(new java.awt.Color(204, 0, 204));
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/sair.png"))); // NOI18N
        btLogout.setText("LOGOUT");
        btLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLogout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btLogout.setIconTextGap(20);
        btLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLogoutMouseExited(evt);
            }
        });
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btSobre.setBackground(new java.awt.Color(241, 241, 241));
        btSobre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSobre.setForeground(new java.awt.Color(204, 0, 204));
        btSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/informacoes.png"))); // NOI18N
        btSobre.setText("SOBRE");
        btSobre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSobre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btSobre.setIconTextGap(35);
        btSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSobreMouseExited(evt);
            }
        });
        btSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobreActionPerformed(evt);
            }
        });

        btnCto.setBackground(new java.awt.Color(241, 241, 241));
        btnCto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCto.setForeground(new java.awt.Color(204, 0, 204));
        btnCto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/caixa-de-entrega.png"))); // NOI18N
        btnCto.setText("CTO E CEO");
        btnCto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnCto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCto.setIconTextGap(10);
        btnCto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCtoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCtoMouseExited(evt);
            }
        });
        btnCto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesAct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(btSobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(btnCto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDesAct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addComponent(btnCto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(251, Short.MAX_VALUE)))
        );

        jPanel3.setMinimumSize(new java.awt.Dimension(512, 101));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(512, 101));

        lbUsuario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(204, 0, 204));
        lbUsuario.setText("Usuário:");

        lbPrevilegio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbPrevilegio.setForeground(new java.awt.Color(204, 0, 204));
        lbPrevilegio.setText("Previlégio:");

        lbUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbUsuario1.setForeground(new java.awt.Color(204, 0, 204));
        lbUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsuario1.setText("MODO TÉCNICO");
        lbUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/do-utilizador.png"))); // NOI18N
        jLabel2.setText("Perfil");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Tema:");

        cbTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTemas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        cbTemas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTemasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lbUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPrevilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbPrevilegio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbTemas, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );

        jPanel4.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Logo Empresa.png"))); // NOI18N
        jLabel1.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pFundoLayout = new javax.swing.GroupLayout(pFundo);
        pFundo.setLayout(pFundoLayout);
        pFundoLayout.setHorizontalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFundoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
        );
        pFundoLayout.setVerticalGroup(
            pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFundoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(pFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 691));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/A0.jpg"))); // NOI18N
        lbFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbFundo.setMaximumSize(new java.awt.Dimension(0, 0));
        lbFundo.setMinimumSize(new java.awt.Dimension(0, 0));
        lbFundo.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 2256, 1504));

        setSize(new java.awt.Dimension(1402, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Dados().RegistrarLogs(getUsuario(), "FEZ LOGOUT DO SISTEMA");
        new Login().setVisible(true);
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        new Dados().RegistrarLogs(getUsuario(), "ENCERROU O SISTEMA");
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoMouseEntered
        // TODO add your handling code here:
        btNovo.setBackground(Color.GREEN);
        btNovo.setForeground(Color.BLACK);
    }//GEN-LAST:event_btNovoMouseEntered

    private Color fundo;
    private Color letra;

    private void btNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNovoMouseExited
        // TODO add your handling code here:
        btNovo.setBackground(getCorBotao());
        btNovo.setForeground(getCorLetra());
    }//GEN-LAST:event_btNovoMouseExited

    private void btTodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTodosMouseEntered
        // TODO add your handling code here:
        btTodos.setBackground(Color.GREEN);
        btTodos.setForeground(Color.BLACK);
    }//GEN-LAST:event_btTodosMouseEntered

    private void btTodosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTodosMouseExited
        // TODO add your handling code here:
        btTodos.setBackground(getCorBotao());
        btTodos.setForeground(letra);
    }//GEN-LAST:event_btTodosMouseExited

    private void btDesActMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesActMouseEntered
        // TODO add your handling code here:
        btDesAct.setBackground(Color.GREEN);
        btDesAct.setForeground(Color.BLACK);
    }//GEN-LAST:event_btDesActMouseEntered

    private void btDesActMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesActMouseExited
        // TODO add your handling code here:
        btDesAct.setBackground(getCorBotao());
        btDesAct.setForeground(letra);
    }//GEN-LAST:event_btDesActMouseExited

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        NovoTec menu = new NovoTec();
        menu.setIdUsuario(idUsuario);
        menu.setIdTema(idTema);
        menu.SetCorBotoes(CorBotao, CorLetra);
        menu.setVisible(true);

    }//GEN-LAST:event_btNovoActionPerformed

    private void btLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseEntered
        // TODO add your handling code here:
        btLogout.setBackground(Color.GREEN);
        btLogout.setForeground(Color.BLACK);
    }//GEN-LAST:event_btLogoutMouseEntered

    private void btLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLogoutMouseExited
        // TODO add your handling code here:
        btLogout.setBackground(getCorBotao());
        btLogout.setForeground(letra);
    }//GEN-LAST:event_btLogoutMouseExited

    private void btExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseEntered
        // TODO add your handling code here:
        btExit.setBackground(Color.RED);
        btExit.setForeground(Color.GREEN);
    }//GEN-LAST:event_btExitMouseEntered

    private void btExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseExited
        // TODO add your handling code here:
        btExit.setBackground(getCorBotao());
        btExit.setForeground(letra);
    }//GEN-LAST:event_btExitMouseExited

    private void btTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodosActionPerformed
        // TODO add your handling code here:
        Clientes client = new Clientes();
        client.setIdUsuario(getIdUsuario());
        client.setPrevilegio(getPrevilegio());
        client.setIdTema(idTema);
        client.setVisible(true);
    }//GEN-LAST:event_btTodosActionPerformed

    private void btDesActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesActActionPerformed
        // TODO add your handling code here:

        AdmAcoes ce = new AdmAcoes();
        ce.setIdUsuario(getIdUsuario());
        ce.setIdTema(idTema);
        ce.setVisible(true);

    }//GEN-LAST:event_btDesActActionPerformed

    private void btSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSobreMouseEntered
        // TODO add your handling code here:
        btSobre.setBackground(Color.GREEN);
        btSobre.setForeground(Color.BLACK);
    }//GEN-LAST:event_btSobreMouseEntered

    private void btSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSobreMouseExited
        // TODO add your handling code here:
        btSobre.setBackground(getCorBotao());
        btSobre.setForeground(letra);
    }//GEN-LAST:event_btSobreMouseExited

    private void btSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobreActionPerformed
        // TODO add your handling code here:X
        Sobre s = new Sobre();
        s.setVisible(true);
    }//GEN-LAST:event_btSobreActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        MeuPerfil perfil = new MeuPerfil();
        perfil.setIdUsuario(getIdUsuario());
        perfil.setIdTema(idTema);
        perfil.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnCtoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCtoMouseEntered
        // TODO add your handling code here:
        btnCto.setBackground(Color.GREEN);
        btnCto.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCtoMouseEntered

    private void btnCtoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCtoMouseExited
        // TODO add your handling code here:
        btnCto.setBackground(getCorBotao());
        btnCto.setForeground(letra);
    }//GEN-LAST:event_btnCtoMouseExited

    private void btnCtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtoActionPerformed
        // TODO add your handling code here:
        GerenciaCTO cto = new GerenciaCTO();
        cto.setIdUsuario(idUsuario);
        cto.setPrevilegio2(previlegio);
        cto.setIdTema(idTema);
        cto.setVisible(true);
    }//GEN-LAST:event_btnCtoActionPerformed

    private void cbTemasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTemasItemStateChanged
        // TODO add your handling code here:
        idTema = cbTemas.getSelectedIndex();
        if (idTema == 0) {
            setCorBotao(new Color(0xf1f1f1));
            setCorLetra(new Color(0xcc00cc));
            setCorFundo(new Color(0xfbfbfc));
            SetCorBotoes(CorBotao, CorLetra);
            String imageName = "/imagens/A" + cbTemas.getSelectedIndex() + ".jpg";
            if (cbTemas.getSelectedIndex() == 0) {
                lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
            }
        } else {
            setCorBotao(new Color(0x241f24));
            setCorLetra(new Color(0xcc00cc));
            setCorFundo(new Color(0x110e11));
            SetCorBotoes(CorBotao, CorLetra);
            String imageName = "/imagens/A" + cbTemas.getSelectedIndex() + ".jpg";
            if (cbTemas.getSelectedIndex() == 1) {
                lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
            }
        }
    }//GEN-LAST:event_cbTemasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModoTécnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModoTécnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModoTécnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModoTécnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModoTécnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDesAct;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSobre;
    private javax.swing.JButton btTodos;
    private javax.swing.JButton btnCto;
    private javax.swing.JComboBox<String> cbTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbPrevilegio;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuario1;
    private javax.swing.JPanel pFundo;
    // End of variables declaration//GEN-END:variables
}
