/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Objetos.ClientesOBJ;
import Objetos.Dados;
import Objetos.PacoteOBJ;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cusodio
 */
public class AdmAcoes extends javax.swing.JFrame {
    
    private int idUsuario;
    private int idTema;
    
    public int getIdTema() {
        return idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            Tabela.setBackground(new Color(0x241f24));
            Tabela.setForeground(new Color(0xCC00CC));
            taNota.setBackground(new Color(0x241f24));
            btnCancelar.setBackground(new Color(0x241f24));
            btnVoltar.setBackground(new Color(0x241f24));
            btnActDes.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0xCC00CC));
        }
    }
    
    public int getIdUsuario() {
        return idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * Creates new form AdmAcoes
     */
    public AdmAcoes() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        tb.setRowCount(0);
        List<Objetos.ClientesOBJ> cliente = new Dados().AllRacionar();
        List<PacoteOBJ> pac = new Dados().Pacotes();
        for (PacoteOBJ paco : pac) {
            cbPacote.addItem(paco.getNome());
        }
        for (ClientesOBJ clientes : cliente) {
            String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), clientes.getInformação()};
            tb.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnActDes = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNota = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nacionalidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Serviço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Endereço = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Contacto = new javax.swing.JTextField();
        whatsapp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        GPON = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        vlan = new javax.swing.JTextField();
        cbPacote = new javax.swing.JComboBox<>();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(860, 622));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(863, 623));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("CLIENTES PARA ATIVAR E DESATIVAR");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 39));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 830, 40));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "AÇÕES"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActDes.setBackground(new java.awt.Color(242, 242, 242));
        btnActDes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActDes.setForeground(new java.awt.Color(204, 0, 204));
        btnActDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lista-de-afazeres.png"))); // NOI18N
        btnActDes.setText("...");
        btnActDes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnActDes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnActDes.setIconTextGap(10);
        btnActDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActDesActionPerformed(evt);
            }
        });
        jPanel3.add(btnActDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, 60));

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setIconTextGap(10);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, 60));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        taNota.setEditable(false);
        taNota.setBackground(new java.awt.Color(0, 0, 0));
        taNota.setColumns(20);
        taNota.setLineWrap(true);
        taNota.setRows(5);
        taNota.setWrapStyleWord(true);
        taNota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        taNota.setDisabledTextColor(new java.awt.Color(204, 0, 204));
        taNota.setEnabled(false);
        taNota.setOpaque(false);
        jScrollPane2.setViewportView(taNota);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 270, 140));

        jLabel14.setText("NOTA DE DESATIVAÇÃO OU ATIVAÇÃO");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 20));

        btnCancelar.setBackground(new java.awt.Color(242, 242, 242));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 0, 204));
        btnCancelar.setText("CANCELAR CLIENTE");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 290, 320));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        Tabela.setBackground(new java.awt.Color(215, 222, 230));
        Tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.setGridColor(new java.awt.Color(204, 0, 204));
        Tabela.setOpaque(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setMinWidth(50);
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            Tabela.getColumnModel().getColumn(0).setMaxWidth(50);
            Tabela.getColumnModel().getColumn(2).setMinWidth(200);
            Tabela.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 520, 290));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 540, 320));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "INFORMAÇÃO DO CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("NOME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 78, 26));

        Nome.setEditable(false);
        Nome.setBackground(new java.awt.Color(215, 222, 230));
        Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nome.setBorder(null);
        jPanel2.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 339, 27));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("NACIONALIDADE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 161, 26));

        Nacionalidade.setEditable(false);
        Nacionalidade.setBackground(new java.awt.Color(215, 222, 230));
        Nacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nacionalidade.setBorder(null);
        jPanel2.add(Nacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 161, 27));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("SERVIÇO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 132, 26));

        Serviço.setEditable(false);
        Serviço.setBackground(new java.awt.Color(215, 222, 230));
        Serviço.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Serviço.setBorder(null);
        jPanel2.add(Serviço, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 132, 27));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("ENDEREÇO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 313, 25));

        Endereço.setEditable(false);
        Endereço.setBackground(new java.awt.Color(215, 222, 230));
        Endereço.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Endereço.setBorder(null);
        jPanel2.add(Endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 340, 27));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("E-MAIL");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 293, 25));

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(215, 222, 230));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setBorder(null);
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 350, 27));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("CONTACTOS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 147, 22));

        Contacto.setEditable(false);
        Contacto.setBackground(new java.awt.Color(215, 222, 230));
        Contacto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Contacto.setBorder(null);
        jPanel2.add(Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 162, 27));

        whatsapp.setEditable(false);
        whatsapp.setBackground(new java.awt.Color(215, 222, 230));
        whatsapp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        whatsapp.setBorder(null);
        jPanel2.add(whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 160, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("PACOTE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 70, 22));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("WHATSAPP");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("B.I");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 120, 30));

        BI.setEditable(false);
        BI.setBackground(new java.awt.Color(215, 222, 230));
        BI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BI.setBorder(null);
        jPanel2.add(BI, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 170, 27));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("GPON");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 70, 22));

        GPON.setEditable(false);
        GPON.setBackground(new java.awt.Color(215, 222, 230));
        GPON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GPON.setBorder(null);
        jPanel2.add(GPON, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 110, 27));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 0));
        jLabel13.setText("VLAN");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 50, 30));

        vlan.setEditable(false);
        vlan.setBackground(new java.awt.Color(215, 222, 230));
        vlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vlan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vlan.setBorder(null);
        jPanel2.add(vlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 50, 30));

        cbPacote.setBackground(new java.awt.Color(215, 222, 230));
        cbPacote.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jPanel2.add(cbPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 840, 230));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel1.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActDesActionPerformed
        
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        if (Tabela.getSelectedRow() != -1) {
            int linha = Tabela.getSelectedRow();
            int id = Integer.parseInt(tb.getValueAt(linha, 0).toString());
            
            int cod = new Dados().BuscarIdHistorico(id);
            
            if (btnActDes.getText().equalsIgnoreCase("Desativar")) {
                
                if (new Dados().atualizarHistorico(cod, new Dados().getNomeUsuário(getIdUsuario()))) {
                    if (new Dados().Desativar(new Dados().getNomeUsuário(getIdUsuario()), id) && new Dados().Desracionar(id)) {
                        JOptionPane.showMessageDialog(null, "Cliente Desativado!");
                    }
                }
            } else {
                if (new Dados().atualizarHistorico(cod, new Dados().getNomeUsuário(getIdUsuario()))) {
                    if (new Dados().Ativar(new Dados().getNomeUsuário(getIdUsuario()), id) && new Dados().Desracionar(id)) {
                        JOptionPane.showMessageDialog(null, "Cliente Activado!");
                    }
                }
            }
            tb.setRowCount(0);
            List<Objetos.ClientesOBJ> cliente = new Dados().AllRacionar();
            
            for (Objetos.ClientesOBJ clientes : cliente) {
                String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), clientes.getInformação()};
                tb.addRow(dados);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnActDesActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        int linha = Tabela.getSelectedRow();
        String n = tb.getValueAt(linha, 1).toString();
        int id = Integer.parseInt(tb.getValueAt(linha, 0).toString());
        List<Objetos.ClientesOBJ> cliente = new Dados().Todos();
        
        if (linha != -1) {
            for (Objetos.ClientesOBJ clientes : cliente) {
                if (n.equalsIgnoreCase(clientes.getNome())) {
                    Nome.setText(clientes.getNome());
                    Nacionalidade.setText(clientes.getNacionalidade());
                    Endereço.setText(clientes.getEndereço());
                    Email.setText(clientes.getEmail());
                    Contacto.setText(clientes.getTelefone());
                    cbPacote.setSelectedIndex(clientes.getPacote() - 1);
                    Serviço.setText(clientes.getServiço());
                    BI.setText(clientes.getBI());
                    GPON.setText(clientes.getGPON());
                    if (clientes.getInformação().equalsIgnoreCase("ACTIVADO")) {
                        btnActDes.setText("DESATIVAR");
                    } else {
                        btnActDes.setText("ACTIVAR");
                    }
                    
                    taNota.setText(new Dados().BuscarNota(id));
                    
                    vlan.setText(clientes.getVlan());
                }
            }
        } else {
            Nome.setText("");
            Nacionalidade.setText("");
            Endereço.setText("");
            Email.setText("");
            Contacto.setText("");
            cbPacote.setSelectedIndex(0);
            Serviço.setText("");
            btnActDes.setText("...");
            GPON.setText("");
            BI.setText("");
            vlan.setText("");
        }
    }//GEN-LAST:event_TabelaMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        Nome.setText("");
        Nacionalidade.setText("");
        Endereço.setText("");
        Email.setText("");
        Contacto.setText("");
        cbPacote.setSelectedIndex(0);
        Serviço.setText("");
        GPON.setText("");
        BI.setText("");
        btnActDes.setText("...");
        vlan.setText("");
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked
    int x, y;
    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        if (Tabela.getSelectedRow() != -1) {
            int linha = Tabela.getSelectedRow();
            int id = Integer.parseInt(tb.getValueAt(linha, 0).toString());
            int cod = new Dados().BuscarIdHistorico(id);
            
            if (new Dados().atualizarHistorico(cod, "CANCELADO -" + new Dados().getNomeUsuário(getIdUsuario()))) {
                if (new Dados().CancelarAtivaçãoDesativação(new Dados().getNomeUsuário(getIdUsuario()), id) && new Dados().Desracionar(id)) {
                    JOptionPane.showMessageDialog(null, "Ativação ou Desativação Cancelada!");
                }
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmAcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmAcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BI;
    private javax.swing.JTextField Contacto;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Endereço;
    private javax.swing.JTextField GPON;
    private javax.swing.JTextField Nacionalidade;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Serviço;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnActDes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbPacote;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextArea taNota;
    private javax.swing.JTextField vlan;
    private javax.swing.JTextField whatsapp;
    // End of variables declaration//GEN-END:variables
}
