/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Objetos.Dados;
import Objetos.EquipamentoOBJ;
import Objetos.FornecedoresOBJ;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Custodio Quingumba
 */
public class Equipamentos extends javax.swing.JFrame {

    /**
     * Creates new form Equipamentos
     */
    private int idUsuario;
    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            tabela.setBackground(new Color(0x241f24));
            tabela.setForeground(new Color(0xCC00CC));
            btnVoltar.setBackground(new Color(0x241f24));
            cbFornecedor.setBackground(new Color(0x241f24));
            btnAtualizar.setBackground(new Color(0x241f24));
            btnRecarregar.setBackground(new Color(0x241f24));
            btnRegistrar.setBackground(new Color(0x241f24));
            btnQuantidade.setBackground(new Color(0x241f24));
            btnFornecedor.setBackground(new Color(0x241f24));
            btnRemover.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Equipamentos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        List<FornecedoresOBJ> fornecedores = new Dados().TodosFornecedor();
        List<EquipamentoOBJ> equipamento = new Dados().TodosEquipamentos();
        for (FornecedoresOBJ fornecedore : fornecedores) {
            cbFornecedor.addItem(fornecedore.getNome().toUpperCase());
        }
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (EquipamentoOBJ equipamentoOBJ : equipamento) {
            String dados[] = {"" + equipamentoOBJ.getId(), equipamentoOBJ.getNome(), equipamentoOBJ.getFornecedor(), "" + equipamentoOBJ.getQtd()};
            modelo.addRow(dados);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtPreço = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox<>();
        btnRecarregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnFornecedor = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnQuantidade = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIAMENTO DE STOQUE");
        setMinimumSize(new java.awt.Dimension(870, 580));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel4.setOpaque(false);
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, 40));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 840, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "REGISTRO DE EQUIPAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("NOME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("MODELO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("PREÇO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 120, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("FORNECEDOR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, 30));

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 30));

        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtModelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 200, 30));

        txtQtd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtQtd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdKeyTyped(evt);
            }
        });
        jPanel1.add(txtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 120, 30));

        txtPreço.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPreço.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtPreço.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreçoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPreço, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 120, 30));

        btnRegistrar.setBackground(new java.awt.Color(232, 233, 235));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(204, 0, 204));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/finalizado.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 130, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("QUANTIDADE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 120, 30));

        cbFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbFornecedor.setForeground(new java.awt.Color(204, 0, 204));
        cbFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel1.add(cbFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 480, 30));

        btnRecarregar.setBackground(new java.awt.Color(232, 233, 235));
        btnRecarregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRecarregar.setForeground(new java.awt.Color(204, 0, 204));
        btnRecarregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/recarregar.png"))); // NOI18N
        btnRecarregar.setText("RECARREGAR");
        btnRecarregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRecarregar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRecarregar.setIconTextGap(10);
        btnRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecarregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecarregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 160, 50));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 850, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "STOQUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabela.setBackground(new java.awt.Color(215, 222, 230));
        tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tabela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "EQUIPAMENTO", "FORNECEDOR", "QTD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setGridColor(new java.awt.Color(204, 0, 204));
        tabela.setOpaque(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(50);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabela.getColumnModel().getColumn(0).setMaxWidth(50);
            tabela.getColumnModel().getColumn(3).setMinWidth(150);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 670, 300));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 690, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "AÇÕES"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFornecedor.setBackground(new java.awt.Color(232, 233, 235));
        btnFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFornecedor.setForeground(new java.awt.Color(204, 0, 204));
        btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/entregador.png"))); // NOI18N
        btnFornecedor.setText("FORNECEDOR");
        btnFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFornecedor.setMaximumSize(new java.awt.Dimension(73, 23));
        btnFornecedor.setMinimumSize(new java.awt.Dimension(73, 23));
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });
        jPanel3.add(btnFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 50));

        btnRemover.setBackground(new java.awt.Color(232, 233, 235));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(204, 0, 204));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/botao-apagar.png"))); // NOI18N
        btnRemover.setText("REMOVER");
        btnRemover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRemover.setIconTextGap(15);
        btnRemover.setMaximumSize(new java.awt.Dimension(73, 23));
        btnRemover.setMinimumSize(new java.awt.Dimension(73, 23));
        btnRemover.setPreferredSize(new java.awt.Dimension(73, 23));
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 50));

        btnVoltar.setBackground(new java.awt.Color(232, 233, 235));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setIconTextGap(15);
        btnVoltar.setMaximumSize(new java.awt.Dimension(73, 23));
        btnVoltar.setMinimumSize(new java.awt.Dimension(73, 23));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 60));

        btnAtualizar.setBackground(new java.awt.Color(232, 233, 235));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(204, 0, 204));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/atualizar.png"))); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAtualizar.setIconTextGap(10);
        btnAtualizar.setMaximumSize(new java.awt.Dimension(73, 23));
        btnAtualizar.setMinimumSize(new java.awt.Dimension(73, 23));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 50));

        btnQuantidade.setBackground(new java.awt.Color(232, 233, 235));
        btnQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuantidade.setForeground(new java.awt.Color(204, 0, 204));
        btnQuantidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/quantidade.png"))); // NOI18N
        btnQuantidade.setText("QUANTIDADE");
        btnQuantidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnQuantidade.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnQuantidade.setMaximumSize(new java.awt.Dimension(73, 23));
        btnQuantidade.setMinimumSize(new java.awt.Dimension(73, 23));
        btnQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantidadeActionPerformed(evt);
            }
        });
        jPanel3.add(btnQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 50));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 150, 330));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setText("GESTÃO DE EQUIPAMENTOS DA EMPRESA");
        jPanel5.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 30));

        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel5.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            String nome = txtNome.getText().toUpperCase();
            String modelo = txtModelo.getText().toUpperCase();
            int quantidade = Integer.parseInt(txtQtd.getText());
            float preço = Float.parseFloat(txtPreço.getText());
            String fornecedor = cbFornecedor.getSelectedItem().toString().toUpperCase();

            if (new Dados().RegistrarEquipamento(new Dados().getNomeUsuário(getIdUsuario()), new EquipamentoOBJ(0, nome, modelo, quantidade, preço, fornecedor))) {
                JOptionPane.showMessageDialog(null, "FEITO!");
                txtNome.setText("");
                txtModelo.setText("");
                txtPreço.setText("");
                txtQtd.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na interface: " + e);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtQtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyTyped
        char letra = evt.getKeyChar();
        if (!Character.isDigit(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtdKeyTyped

    private void txtPreçoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreçoKeyTyped
        // TODO add your handling code here:
        char letra = evt.getKeyChar();
        String val = "" + letra;
        if ((!Character.isDigit(letra) && letra != '.')) {
            evt.consume();
        } else if (letra == '.') {
            if (txtPreço.getText().contains(".")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtPreçoKeyTyped

    public void DesativarBTN() {
        btnFornecedor.setEnabled(false);
        btnRemover.setEnabled(false);
        btnQuantidade.setEnabled(false);
        btnRegistrar.setEnabled(false);
        btnAtualizar.setText("CONCLUIR");
        txtNome.setEditable(true);
        txtModelo.setEditable(true);
        txtPreço.setEditable(true);
        txtQtd.setEditable(true);
        tabela.setEnabled(false);
    }

    public void ActivarBTN() {
        btnFornecedor.setEnabled(true);
        btnRemover.setEnabled(true);
        btnQuantidade.setEnabled(true);
        btnRegistrar.setEnabled(true);
        btnAtualizar.setText("ATUALIZAR");
        txtNome.setEditable(false);
        txtModelo.setEditable(false);
        txtPreço.setEditable(false);
        txtQtd.setEditable(false);
        tabela.setEnabled(true);
    }


    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            if (btnAtualizar.getText().equalsIgnoreCase("Atualizar")) {
                DesativarBTN();
            } else {
                try {
                    String nome = txtNome.getText().toUpperCase();
                    String modelo = txtModelo.getText().toUpperCase();
                    int quantidade = Integer.parseInt(txtQtd.getText());
                    float preço = Float.parseFloat(txtPreço.getText());
                    String fornecedor = cbFornecedor.getSelectedItem().toString().toUpperCase();

                    if (new Dados().AtualizarEquipamento(new Dados().getNomeUsuário(getIdUsuario()), new EquipamentoOBJ(0, nome, modelo, quantidade, preço, fornecedor))) {
                        JOptionPane.showMessageDialog(null, "FEITO!");
                        txtNome.setText("");
                        txtModelo.setText("");
                        txtPreço.setText("");
                        txtQtd.setText("");

                        List<EquipamentoOBJ> equipamento = new Dados().TodosEquipamentos();
                        DefaultTableModel modelo1 = (DefaultTableModel) tabela.getModel();
                        modelo1.setRowCount(0);
                        for (EquipamentoOBJ equipamentoOBJ : equipamento) {
                            String dados[] = {"" + equipamentoOBJ.getId(), equipamentoOBJ.getNome(), equipamentoOBJ.getFornecedor(), "" + equipamentoOBJ.getQtd()};
                            modelo1.addRow(dados);
                        };
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro na interface: " + e);
                }
                ActivarBTN();
            }
        } else
            JOptionPane.showMessageDialog(null, "SELECIONE UM EQUIPAMENTO NA TABELA!");
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantidadeActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            int id = Integer.parseInt("" + tabela.getValueAt(tabela.getSelectedRow(), 0));
            AddProduto AR = new AddProduto();
            AR.setIdUsuario(idUsuario);
            AR.setIdProduto(id);
            AR.setVisible(true);
        }
    }//GEN-LAST:event_btnQuantidadeActionPerformed

    private void btnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecarregarActionPerformed
        // TODO add your handling code here:
        List<FornecedoresOBJ> fornecedores = new Dados().TodosFornecedor();
        List<EquipamentoOBJ> equipamento = new Dados().TodosEquipamentos();
        cbFornecedor.removeAllItems();
        for (FornecedoresOBJ fornecedore : fornecedores) {
            cbFornecedor.addItem(fornecedore.getNome().toUpperCase());
        }
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (EquipamentoOBJ equipamentoOBJ : equipamento) {
            String dados[] = {"" + equipamentoOBJ.getId(), equipamentoOBJ.getNome(), equipamentoOBJ.getFornecedor(), "" + equipamentoOBJ.getQtd()};
            modelo.addRow(dados);
        }

        btnRegistrar.setEnabled(true);
        txtNome.setText("");
        txtModelo.setText("");
        txtPreço.setText("");
        txtQtd.setText("");
        txtNome.setEditable(true);
        txtModelo.setEditable(true);
        txtPreço.setEditable(true);
        txtQtd.setEditable(true);
    }//GEN-LAST:event_btnRecarregarActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        // TODO add your handling code here:
        ListaDeFornecedores lforn = new ListaDeFornecedores();
        lforn.setIdUsuario(getIdUsuario());
        lforn.setVisible(true);
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (tabela.getSelectedRow() != -1) {
            int id = Integer.parseInt("" + tabela.getValueAt(tabela.getSelectedRow(), 0));
            EquipamentoOBJ eq = new Dados().BuscaEquipamento(id);
            txtNome.setText(eq.getNome());
            txtModelo.setText(eq.getModelo());
            txtPreço.setText("" + eq.getPreço());
            txtQtd.setText("" + eq.getQtd());
            btnRegistrar.setEnabled(false);
            txtNome.setEditable(false);
            txtModelo.setEditable(false);
            txtPreço.setEditable(false);
            txtQtd.setEditable(false);
        } else {
            txtNome.setText("");
            txtModelo.setText("");
            txtPreço.setText("");
            txtQtd.setText("");
            txtNome.setEditable(true);
            txtModelo.setEditable(true);
            txtPreço.setEditable(true);
            txtQtd.setEditable(true);
            btnRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            int id = Integer.parseInt("" + tabela.getValueAt(tabela.getSelectedRow(), 0));
            if (new Dados().ExcluirEquipamento(new Dados().getNomeUsuário(getIdUsuario()), id)) {
                JOptionPane.showMessageDialog(null, "EQUIPAMENTO APAGADO!");
                txtNome.setText("");
                txtModelo.setText("");
                txtPreço.setText("");
                txtQtd.setText("");
                btnRegistrar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1) {
            int id = Integer.parseInt("" + tabela.getValueAt(tabela.getSelectedRow(), 0));
            EquipamentoOBJ eq = new Dados().BuscaEquipamento(id);
            txtNome.setText(eq.getNome());
            txtModelo.setText(eq.getModelo());
            txtPreço.setText("" + eq.getPreço());
            txtQtd.setText("" + eq.getQtd());
            btnRegistrar.setEnabled(false);
            txtNome.setEditable(false);
            txtModelo.setEditable(false);
            txtPreço.setEditable(false);
            txtQtd.setEditable(false);
        } else {
            txtNome.setText("");
            txtModelo.setText("");
            txtPreço.setText("");
            txtQtd.setText("");
            txtNome.setEditable(true);
            txtModelo.setEditable(true);
            txtPreço.setEditable(true);
            txtQtd.setEditable(true);
            btnRegistrar.setEnabled(true);
        }
    }//GEN-LAST:event_jScrollPane1MouseClicked
    int x, y;
    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel4MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnQuantidade;
    private javax.swing.JButton btnRecarregar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreço;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
