/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Objetos.Dados;
import Objetos.FornecedoresOBJ;
import Objetos.TemaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Quingumba
 */
public class Fornecedores extends javax.swing.JFrame {

    /**
     * Creates new form NCliente
     */
    private int idUsuario;
    private Color CorBotao, CorLetra, CorFundo;
    List<TemaOBJ> tema = new ArrayList<>();

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
        if (CorFundo != new Color(0xfbfbfc)) {
            lbTitulo.setForeground(new Color(0xfbfbfc));
        }
    }

    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            btnCancelar.setBackground(new Color(0x241f24));
            btnCadastrar.setBackground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Fornecedores() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        txtContacto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtContaBancária = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEndereço = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtIban = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtContacto2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(793, 570));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContacto.setBackground(new java.awt.Color(232, 233, 235));
        txtContacto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContacto.setForeground(new java.awt.Color(204, 0, 204));
        txtContacto.setBorder(null);
        pFundo.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 200, 34));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Contactos:");
        pFundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("Nome: ");
        pFundo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, 30));

        txtNome.setBackground(new java.awt.Color(232, 233, 235));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(204, 0, 204));
        txtNome.setBorder(null);
        pFundo.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 500, 34));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        pFundo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 500, 10));

        txtContaBancária.setBackground(new java.awt.Color(232, 233, 235));
        txtContaBancária.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContaBancária.setForeground(new java.awt.Color(204, 0, 204));
        txtContaBancária.setBorder(null);
        txtContaBancária.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContaBancáriaMouseClicked(evt);
            }
        });
        pFundo.add(txtContaBancária, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 500, 34));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        pFundo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 500, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Conta Bancária:");
        pFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("Endereço:");
        pFundo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 30));

        txtEndereço.setBackground(new java.awt.Color(232, 233, 235));
        txtEndereço.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEndereço.setForeground(new java.awt.Color(204, 0, 204));
        txtEndereço.setBorder(null);
        pFundo.add(txtEndereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 500, 34));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        pFundo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 500, 10));

        txtIban.setBackground(new java.awt.Color(232, 233, 235));
        txtIban.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIban.setForeground(new java.awt.Color(204, 0, 204));
        txtIban.setBorder(null);
        pFundo.add(txtIban, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 500, 34));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        pFundo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 500, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("IBAN:");
        pFundo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 40));

        txtContacto2.setBackground(new java.awt.Color(232, 233, 235));
        txtContacto2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtContacto2.setForeground(new java.awt.Color(204, 0, 204));
        txtContacto2.setBorder(null);
        pFundo.add(txtContacto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 200, 34));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        pFundo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 200, 10));

        btnCancelar.setBackground(new java.awt.Color(242, 242, 242));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 0, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelar.setIconTextGap(20);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pFundo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 200, 50));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, 40));

        pFundo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, -1));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setText("NOVO FORNECEDOR");
        pFundo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 50));

        btnCadastrar.setBackground(new java.awt.Color(242, 242, 242));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(204, 0, 204));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/finalizado.png"))); // NOI18N
        btnCadastrar.setText("Finalizar");
        btnCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCadastrar.setIconTextGap(10);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        pFundo.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 220, 50));

        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Log.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pFundo.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContaBancáriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContaBancáriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContaBancáriaMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txtNome.getText();
        String contacto = txtContacto.getText();
        if (!txtContacto2.getText().equalsIgnoreCase("") && !txtContacto2.getText().equalsIgnoreCase(" ")) {
            contacto = txtContacto.getText() + " - " + txtContacto2.getText();
        }
        String enderço = txtEndereço.getText();
        String conta = txtContaBancária.getText();
        String IBAN = txtIban.getText();

        if (!nome.equalsIgnoreCase("")) {
            if (new Dados().RegistrarFornecedor(new Dados().getNomeUsuário(getIdUsuario()), new FornecedoresOBJ(0, nome, contacto, enderço, conta, IBAN))) {
                JOptionPane.showMessageDialog(null, "Feito");
                txtNome.setText("");
                txtContacto.setText("");
                txtContacto2.setText("");
                txtContaBancária.setText("");
                txtEndereço.setText("");
                txtIban.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos devidamente!");
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked
    int x, y;
    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pFundo;
    private javax.swing.JTextField txtContaBancária;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtContacto2;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextField txtIban;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
