/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Objetos.ClientesOBJ;
import Objetos.Dados;
import Objetos.PacoteOBJ;
import Objetos.TemaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Custódio Quingumba
 */
public class NovoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NovoCliente
     */
    private String previlegio, usuario;
    private int idUsuario;
    private Color CorBotao, CorLetra, CorFundo;
    List<TemaOBJ> tema = new ArrayList<>();

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
        if (CorFundo != new Color(0xfbfbfc)) {
            lbTitulo.setForeground(new Color(0xfbfbfc));
        }
    }

    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            cbPacote.setBackground(new Color(0x241f24));
            cbServico.setBackground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public NovoCliente() {
        initComponents();
        List<PacoteOBJ> pac = new Dados().Pacotes();
        for (PacoteOBJ paco : pac) {
            cbPacote.addItem(paco.getNome());
        }

        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtNacionalidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBI = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtWhatsapp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        cbServico = new javax.swing.JComboBox<>();
        cbPacote = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtVlan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtGPON1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lbTitulo = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALLCENTER - CADASTRO DE CLIENTES");
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(880, 559));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "INFORMAÇÃO PESSOAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setBackground(new java.awt.Color(216, 223, 233));
        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(204, 0, 204));
        txtNome.setBorder(null);
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 379, 30));

        txtNacionalidade.setBackground(new java.awt.Color(216, 223, 233));
        txtNacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNacionalidade.setForeground(new java.awt.Color(204, 0, 204));
        txtNacionalidade.setBorder(null);
        jPanel1.add(txtNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 182, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("CÓDIO DO DOC.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 158, 26));

        txtBI.setBackground(new java.awt.Color(216, 223, 233));
        txtBI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBI.setForeground(new java.awt.Color(204, 0, 204));
        txtBI.setBorder(null);
        jPanel1.add(txtBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 175, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setText("NACIONALIDADE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 182, 26));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 204, 0));
        jLabel16.setText("NOME:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 379, 24));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 380, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 180, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 170, 10));

        pFundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 860, 100));

        jPanel2.setBackground(new java.awt.Color(107, 98, 98));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "CONTACTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEndereco.setBackground(new java.awt.Color(216, 223, 233));
        txtEndereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEndereco.setForeground(new java.awt.Color(204, 0, 204));
        txtEndereco.setBorder(null);
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 373, 30));

        txtTelefone.setBackground(new java.awt.Color(229, 234, 238));
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(204, 0, 204));
        txtTelefone.setBorder(null);
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 187, 30));

        txtEmail.setBackground(new java.awt.Color(216, 223, 233));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 0, 204));
        txtEmail.setBorder(null);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 372, 30));

        txtWhatsapp.setBackground(new java.awt.Color(229, 234, 238));
        txtWhatsapp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtWhatsapp.setForeground(new java.awt.Color(204, 0, 204));
        txtWhatsapp.setBorder(null);
        jPanel2.add(txtWhatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("CONTACTO");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 174, 29));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("WHATSAPP");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 29));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 0));
        jLabel13.setText("ENDEREÇO");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 373, 28));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setText("E-MAIL");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 372, 28));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 370, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 370, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, -1));

        pFundo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 860, 170));

        jPanel4.setBackground(new java.awt.Color(107, 98, 98));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "DADOS TÉCNICOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbServico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbServico.setForeground(new java.awt.Color(204, 0, 204));
        cbServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INTERNET", "TELEFONIA", "TELEVISÃO", "INTERNET, TELEFONIA,TELEVISÃO" }));
        jPanel4.add(cbServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 186, 30));

        cbPacote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbPacote.setForeground(new java.awt.Color(204, 0, 204));
        jPanel4.add(cbPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 210, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setText("SERVIÇO");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 186, 31));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setText("PACOTE");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 210, 25));

        txtVlan.setBackground(new java.awt.Color(216, 223, 233));
        txtVlan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVlan.setForeground(new java.awt.Color(204, 0, 204));
        txtVlan.setBorder(null);
        jPanel4.add(txtVlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 160, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setText("VLAN");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 160, 29));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 0));
        jLabel20.setText("GPON");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 160, 29));

        txtGPON1.setBackground(new java.awt.Color(241, 246, 249));
        txtGPON1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGPON1.setForeground(new java.awt.Color(204, 0, 204));
        txtGPON1.setBorder(null);
        jPanel4.add(txtGPON1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 160, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 160, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 160, 10));

        pFundo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 860, 110));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("NOVO CLIENTE");
        pFundo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 40));

        btVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btVoltar.setIconTextGap(20);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        pFundo.add(btVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 140, 50));

        btLimpar.setBackground(new java.awt.Color(242, 242, 242));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(204, 0, 204));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/limpar-limpo.png"))); // NOI18N
        btLimpar.setText("LIMPAR CAMPOS");
        btLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        pFundo.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 156, 50));

        btFinalizar.setBackground(new java.awt.Color(242, 242, 242));
        btFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFinalizar.setForeground(new java.awt.Color(204, 0, 204));
        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/finalizado.png"))); // NOI18N
        btFinalizar.setText("FINALIZAR");
        btFinalizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btFinalizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btFinalizar.setIconTextGap(20);
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });
        pFundo.add(btFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 146, 50));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, 40));

        pFundo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, -1));

        lbFundo.setBackground(new java.awt.Color(255, 255, 255));
        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        lbFundo.setMaximumSize(new java.awt.Dimension(860, 571));
        lbFundo.setMinimumSize(new java.awt.Dimension(860, 571));
        lbFundo.setPreferredSize(new java.awt.Dimension(860, 571));
        pFundo.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 560));

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    @SuppressWarnings("empty-statement")
    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText().toUpperCase();
        String nacionalidade = txtNacionalidade.getText().toUpperCase();
        String endereço = "default";
        String BI = txtBI.getText().toUpperCase();
        String telefone = txtTelefone.getText().toUpperCase();
        String serviço = cbServico.getSelectedItem().toString().toUpperCase();
        int pacote = new Dados().getIdPacote(cbPacote.getSelectedItem().toString());
        String whatsapp = "";
        if (!txtEndereco.getText().equalsIgnoreCase("")) {
            endereço = txtEndereco.getText().toUpperCase();
        }
        String email = "default";
        if (!txtEmail.getText().equalsIgnoreCase("")) {
            email = txtEmail.getText().toLowerCase();
        };
        if (txtWhatsapp.getText().equalsIgnoreCase("")) {
            whatsapp = telefone;
        } else {
            whatsapp = txtWhatsapp.getText().toUpperCase();
        }
        ClientesOBJ cliente = new ClientesOBJ(0, nome, nacionalidade, BI, telefone, whatsapp, endereço, email, "DESATIVADO", serviço, pacote, "default", "default", 0);
        if (new Dados().NovoCliente(new Dados().getNomeUsuário(getIdUsuario()), cliente)) {
            txtNome.setText("");
            txtNacionalidade.setText("");
            txtEmail.setText("");
            txtEndereco.setText("");
            txtTelefone.setText("");
            txtWhatsapp.setText("");
        };
    }//GEN-LAST:event_btFinalizarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        txtNome.setText("");
        txtNacionalidade.setText("");
        txtEmail.setText("");
        txtEndereco.setText("");
        txtTelefone.setText("");
        txtWhatsapp.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged
    int x, y;
    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbPacote;
    private javax.swing.JComboBox<String> cbServico;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pFundo;
    private javax.swing.JTextField txtBI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtGPON1;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtVlan;
    private javax.swing.JTextField txtWhatsapp;
    // End of variables declaration//GEN-END:variables
}
