/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import Objetos.ClientesOBJ;
import Objetos.Dados;
import Objetos.DiaPagamentoOBJ;
import Objetos.PacoteOBJ;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Custódio Quingumba
 */
public class Varredura extends javax.swing.JFrame {

    private int idUsuario;
    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            Tabela.setBackground(new Color(0x241f24));
            taNota.setBackground(new Color(0x241f24));
            Tabela.setForeground(new Color(0xCC00CC));
            btnActDes.setBackground(new Color(0x241f24));
            btnVoltar.setBackground(new Color(0x241f24));
            btnAtualizar.setBackground(new Color(0x241f24));
            btnActDes.setBackground(new Color(0x241f24));
            btnImprimir.setBackground(new Color(0x241f24));
            btnPagamentos.setBackground(new Color(0x241f24));
            btnPagar.setBackground(new Color(0x241f24));
            btnRemover.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
        String nome = new Dados().getUsuário(idUsuario).getNome();
        String previlegio = new Dados().getPrevilegString(nome);
        if (previlegio.equalsIgnoreCase("T")) {
            btnAtualizar.setEnabled(true);
        }
        if (previlegio.equalsIgnoreCase("A")) {
            btnAtualizar.setEnabled(true);
        }
    }

    /**
     * Creates new form Ativos
     */
    public Varredura() {
        initComponents();
        Dias = new Dados().BuscarDiaAtual();
        chekAti.setSelected(true);
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());

        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        tb.setRowCount(0);
        List<Objetos.ClientesOBJ> clientesActivados = new Dados().Ativos();
        List<Objetos.ClientesOBJ> clientesDesativados = new Dados().Desativados();
        List<PacoteOBJ> pacotes = new Dados().Pacotes();
        for (PacoteOBJ pacote : pacotes) {
            cbPacote.addItem(pacote.getNome());
        }
        if (chekAti.isSelected()) {
            for (Objetos.ClientesOBJ clientes : clientesActivados) {
                String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                tb.addRow(dados);
            }
        } else if (chekDes.isSelected()) {
            for (Objetos.ClientesOBJ clientes : clientesDesativados) {
                String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                tb.addRow(dados);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNota = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnPagamentos = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnActDes = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        chekAti = new javax.swing.JCheckBox();
        chekDes = new javax.swing.JCheckBox();
        lbTitulo = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nacionalidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Serviço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Endereço = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Contacto = new javax.swing.JTextField();
        whatsapp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        GPON = new javax.swing.JTextField();
        vlan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbPacote = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ALLCENTER - CLIENTES ATIVOS");
        setMaximumSize(new java.awt.Dimension(814, 690));
        setMinimumSize(new java.awt.Dimension(814, 690));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "CLIENTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        Tabela.setBackground(new java.awt.Color(215, 222, 230));
        Tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        Tabela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "DIA DE PAGAMENTO", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.setGridColor(new java.awt.Color(204, 0, 204));
        Tabela.setOpaque(false);
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setMinWidth(50);
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            Tabela.getColumnModel().getColumn(0).setMaxWidth(50);
            Tabela.getColumnModel().getColumn(1).setMinWidth(350);
            Tabela.getColumnModel().getColumn(1).setPreferredWidth(350);
            Tabela.getColumnModel().getColumn(2).setMinWidth(120);
            Tabela.getColumnModel().getColumn(2).setPreferredWidth(120);
            Tabela.getColumnModel().getColumn(2).setMaxWidth(120);
            Tabela.getColumnModel().getColumn(3).setMinWidth(100);
            Tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
            Tabela.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 610, 340));

        jScrollPane2.setOpaque(false);

        taNota.setColumns(10);
        taNota.setForeground(new java.awt.Color(204, 0, 204));
        taNota.setLineWrap(true);
        taNota.setRows(1);
        taNota.setTabSize(1);
        taNota.setWrapStyleWord(true);
        taNota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        taNota.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        taNota.setOpaque(false);
        jScrollPane2.setViewportView(taNota);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 190, 310));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setText("NOTA DE DESATIVAÇÃO OU ATIVAÇÃO");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 16, 190, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 830, 370));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "ACÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPagamentos.setBackground(new java.awt.Color(242, 242, 242));
        btnPagamentos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagamentos.setForeground(new java.awt.Color(204, 0, 204));
        btnPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnPagamentos.setText("PAGAMENTOS");
        btnPagamentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnPagamentos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPagamentos.setIconTextGap(30);
        btnPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentosActionPerformed(evt);
            }
        });
        jPanel3.add(btnPagamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 50));

        btnAtualizar.setBackground(new java.awt.Color(242, 242, 242));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(204, 0, 204));
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/atualizar.png"))); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnAtualizar.setEnabled(false);
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAtualizar.setIconTextGap(50);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 50));

        btnRemover.setBackground(new java.awt.Color(242, 242, 242));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(204, 0, 204));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/botao-apagar.png"))); // NOI18N
        btnRemover.setText("REMOVER");
        btnRemover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRemover.setIconTextGap(50);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 50));

        btnActDes.setBackground(new java.awt.Color(242, 242, 242));
        btnActDes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActDes.setForeground(new java.awt.Color(204, 0, 204));
        btnActDes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/lista-de-afazeres.png"))); // NOI18N
        btnActDes.setText("...");
        btnActDes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnActDes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnActDes.setIconTextGap(40);
        btnActDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActDesActionPerformed(evt);
            }
        });
        jPanel3.add(btnActDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 50));

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setIconTextGap(50);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, 50));

        btnPagar.setBackground(new java.awt.Color(242, 242, 242));
        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(204, 0, 204));
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pagar.png"))); // NOI18N
        btnPagar.setText("PAGAR");
        btnPagar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnPagar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPagar.setIconTextGap(70);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel3.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 50));

        btnImprimir.setBackground(new java.awt.Color(242, 242, 242));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(204, 0, 204));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/imprimir.png"))); // NOI18N
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnImprimir.setIconTextGap(50);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel3.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, 50));

        chekAti.setBackground(new java.awt.Color(215, 222, 230));
        chekAti.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        chekAti.setForeground(new java.awt.Color(51, 204, 0));
        chekAti.setText("ACTIVADOS");
        chekAti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        chekAti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekAtiActionPerformed(evt);
            }
        });
        jPanel3.add(chekAti, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 40));

        chekDes.setBackground(new java.awt.Color(215, 222, 230));
        chekDes.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        chekDes.setForeground(new java.awt.Color(51, 204, 0));
        chekDes.setText("DESATIVADOS");
        chekDes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        chekDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chekDesActionPerformed(evt);
            }
        });
        jPanel3.add(chekDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 230, 560));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("CLIENTES ATIVADOS E DASTIVADOS");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 39));

        txtPesquisa.setBackground(new java.awt.Color(215, 222, 230));
        txtPesquisa.setForeground(new java.awt.Color(204, 0, 204));
        txtPesquisa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPesquisa.setText("Pesquisar . . .");
        txtPesquisa.setToolTipText("");
        txtPesquisa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 230, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "INFORMAÇÃO DO CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("NOME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 78, 26));

        Nome.setEditable(false);
        Nome.setBackground(new java.awt.Color(215, 222, 230));
        Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nome.setForeground(new java.awt.Color(204, 0, 204));
        Nome.setBorder(null);
        jPanel2.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 339, 27));

        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("NACIONALIDADE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 161, 26));

        Nacionalidade.setEditable(false);
        Nacionalidade.setBackground(new java.awt.Color(215, 222, 230));
        Nacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nacionalidade.setForeground(new java.awt.Color(204, 0, 204));
        Nacionalidade.setBorder(null);
        jPanel2.add(Nacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 200, 27));

        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("SERVIÇO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 132, 26));

        Serviço.setEditable(false);
        Serviço.setBackground(new java.awt.Color(215, 222, 230));
        Serviço.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Serviço.setForeground(new java.awt.Color(204, 0, 204));
        Serviço.setBorder(null);
        jPanel2.add(Serviço, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 110, 30));

        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("ENDEREÇO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 104, 313, 25));

        Endereço.setEditable(false);
        Endereço.setBackground(new java.awt.Color(215, 222, 230));
        Endereço.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Endereço.setForeground(new java.awt.Color(204, 0, 204));
        Endereço.setBorder(null);
        jPanel2.add(Endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, 27));

        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("E-MAIL");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 293, 25));

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(215, 222, 230));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(204, 0, 204));
        Email.setBorder(null);
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 390, 27));

        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("CONTACTOS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 147, 22));

        Contacto.setEditable(false);
        Contacto.setBackground(new java.awt.Color(215, 222, 230));
        Contacto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Contacto.setForeground(new java.awt.Color(204, 0, 204));
        Contacto.setBorder(null);
        jPanel2.add(Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 162, 30));

        whatsapp.setEditable(false);
        whatsapp.setBackground(new java.awt.Color(215, 222, 230));
        whatsapp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        whatsapp.setForeground(new java.awt.Color(204, 0, 204));
        whatsapp.setBorder(null);
        jPanel2.add(whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 160, 30));

        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("PACOTE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 70, 22));

        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("WHATSAPP");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("B.I");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 120, 22));

        BI.setEditable(false);
        BI.setBackground(new java.awt.Color(215, 222, 230));
        BI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BI.setForeground(new java.awt.Color(204, 0, 204));
        BI.setBorder(null);
        jPanel2.add(BI, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 170, 27));

        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setText("GPON");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 70, 22));

        GPON.setEditable(false);
        GPON.setBackground(new java.awt.Color(215, 222, 230));
        GPON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GPON.setForeground(new java.awt.Color(204, 0, 204));
        GPON.setBorder(null);
        jPanel2.add(GPON, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 110, 30));

        vlan.setEditable(false);
        vlan.setBackground(new java.awt.Color(215, 222, 230));
        vlan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vlan.setForeground(new java.awt.Color(204, 0, 204));
        vlan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vlan.setBorder(null);
        jPanel2.add(vlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 50, 30));

        jLabel13.setForeground(new java.awt.Color(51, 204, 0));
        jLabel13.setText("VLAN");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 50, -1));

        cbPacote.setBackground(new java.awt.Color(215, 222, 230));
        cbPacote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbPacote.setForeground(new java.awt.Color(204, 0, 204));
        jPanel2.add(cbPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 830, 240));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, -1));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        lbFundo.setMaximumSize(new java.awt.Dimension(810, 690));
        lbFundo.setMinimumSize(new java.awt.Dimension(810, 690));
        lbFundo.setPreferredSize(new java.awt.Dimension(810, 690));
        jPanel1.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private List<DiaPagamentoOBJ> Dias;

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        int linha = Tabela.getSelectedRow();
        String n = tb.getValueAt(linha, 1).toString();
        List<Objetos.ClientesOBJ> cliente = new Dados().Todos();

        if (linha != -1) {
            for (Objetos.ClientesOBJ clientes : cliente) {
                if (n.equalsIgnoreCase(clientes.getNome())) {
                    Nome.setText(clientes.getNome());
                    Nacionalidade.setText(clientes.getNacionalidade());
                    Endereço.setText(clientes.getEndereço());
                    Email.setText(clientes.getEmail());
                    Contacto.setText(clientes.getTelefone());
                    cbPacote.setSelectedIndex(clientes.getPacote() - 1);
                    Serviço.setText(clientes.getServiço());
                    BI.setText(clientes.getBI());
                    GPON.setText(clientes.getGPON());
                    vlan.setText(clientes.getVlan());
                    if (clientes.getInformação().equalsIgnoreCase("ACTIVADO")) {
                        btnActDes.setText("DESATIVAR");
                    } else if (clientes.getInformação().equalsIgnoreCase("DESATIVADO")) {
                        btnActDes.setText("ACTIVAR");
                    }
                }

            }
        } else {
            Nome.setText("");
            Nacionalidade.setText("");
            Endereço.setText("");
            Email.setText("");
            Contacto.setText("");
            cbPacote.setSelectedIndex(0);
            Serviço.setText("");
            BI.setText("");
            GPON.setText("");
            btnActDes.setText("...");
            vlan.setText("");
            taNota.setText("");
        }

    }//GEN-LAST:event_TabelaMouseClicked
    int x, y;
    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        Nome.setText("");
        Nacionalidade.setText("");
        Endereço.setText("");
        Email.setText("");
        Contacto.setText("");
        cbPacote.setSelectedIndex(0);
        Serviço.setText("");
        btnActDes.setText("...");
        vlan.setText("");
        taNota.setText("");
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void AtivarEdição() {
        Nome.setEditable(true);
        Nacionalidade.setEditable(true);
        Contacto.setEditable(true);
        Email.setEditable(true);
        whatsapp.setEditable(true);
        cbPacote.setEditable(true);
        Endereço.setEditable(true);
        BI.setEditable(true);
        GPON.setEditable(true);
        Serviço.setEditable(true);
        btnAtualizar.setText("CONCLUIR");
        btnPagamentos.setEnabled(false);
        btnRemover.setEnabled(false);
        btnVoltar.setEnabled(false);
        btnPagar.setEnabled(false);
        btnImprimir.setEnabled(false);
        btnActDes.setEnabled(false);
        vlan.setEditable(true);
    }

    private void DesativarEdição() {
        Nome.setEditable(false);
        Nacionalidade.setEditable(false);
        Contacto.setEditable(false);
        Email.setEditable(false);
        whatsapp.setEditable(false);
        cbPacote.setEditable(false);
        Endereço.setEditable(false);
        BI.setEditable(false);
        GPON.setEditable(false);
        Serviço.setEditable(false);
        btnAtualizar.setText("ATUALIZAR");
        btnPagamentos.setEnabled(true);
        btnRemover.setEnabled(true);
        btnVoltar.setEnabled(true);
        btnPagar.setEnabled(true);
        btnImprimir.setEnabled(true);
        btnActDes.setEnabled(true);
        vlan.setEditable(false);
    }

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();

        if (Tabela.getSelectedRow() != -1) {
            if (btnAtualizar.getText().equalsIgnoreCase("ATUALIZAR")) {
                AtivarEdição();
            } else if (btnAtualizar.getText().equalsIgnoreCase("CONCLUIR")) {

                String nome = Nome.getText().toUpperCase();
                String nacionalidade = Nacionalidade.getText().toUpperCase();
                String endereço = Endereço.getText().toUpperCase();
                String Bi = this.BI.getText().toUpperCase();
                String telefone = Contacto.getText().toUpperCase();
                String serviço = Serviço.getText().toUpperCase();
                int pacote = cbPacote.getSelectedIndex() + 1;
                String Whatsapp = this.whatsapp.getText().toUpperCase();
                String Gpon = GPON.getText().toUpperCase();
                String email = this.Email.getText().toLowerCase();
                String Vlan = this.vlan.getText();

                int id = Integer.parseInt(tb.getValueAt(Tabela.getSelectedRow(), 0).toString());

                if (new Dados().AtualizarCliente(new Dados().getNomeUsuário(getIdUsuario()), new ClientesOBJ(id, nome, nacionalidade, Bi, telefone, Whatsapp, endereço, email, "DESATIVADO", serviço, pacote, Gpon, Vlan, 0))) {
                    DesativarEdição();
                }
                tb.setRowCount(0);
                List<Objetos.ClientesOBJ> cliente = new Dados().Todos();
                for (Objetos.ClientesOBJ clientes : cliente) {
                    String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                    tb.addRow(dados);
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        if (Tabela.getSelectedRow() != -1) {
            int linha = Tabela.getSelectedRow();
            int id = Integer.parseInt(tb.getValueAt(linha, 0).toString());
            String snh = JOptionPane.showInputDialog(null, "Insira a senha Raiz");
            if (new Dados().confirmar(snh)) {
                if (new Dados().Apagar(new Dados().getNomeUsuário(getIdUsuario()), id)) {
                    JOptionPane.showMessageDialog(null, "Cliente Removido!");
                }
                tb.setRowCount(0);
                List<Objetos.ClientesOBJ> cliente = new Dados().Todos();

                for (Objetos.ClientesOBJ clientes : cliente) {
                    String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                    tb.addRow(dados);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Senha Raiz errada! Processo Cancelado.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnActDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActDesActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        if (Tabela.getSelectedRow() != -1) {

            int linha = Tabela.getSelectedRow();

            int id = Integer.parseInt(tb.getValueAt(linha, 0).toString());

            if (btnActDes.getText().equalsIgnoreCase("Desativar")) {
                String nota = taNota.getText();
                if (nota.isEmpty() || nota.equalsIgnoreCase("") || nota.equalsIgnoreCase(" ")) {
                    JOptionPane.showMessageDialog(null, "Insira Nota de Desativação!");
                } else {
                    if (new Dados().Racionar(id, "Desactivar", nota) && new Dados().AddHistorico(id, new Dados().getNomeCliente(id), new Dados().getNomeUsuário(getIdUsuario()), "DESACTIVAR", nota)) {
                        taNota.setText("");
                        JOptionPane.showMessageDialog(null, "Cliente em processamento Des!");
                    }
                }

            } else {
                String nota = taNota.getText();
                if (nota.isEmpty() || nota.equalsIgnoreCase("") || nota.equalsIgnoreCase(" ")) {
                    JOptionPane.showMessageDialog(null, "Insira Nota de Desativação!");
                } else {
                    if (new Dados().Racionar(id, "Actiar", nota) && new Dados().AddHistorico(id, new Dados().getNomeCliente(id), new Dados().getNomeUsuário(getIdUsuario()), "ACTIVAR", nota)) {
                        taNota.setText("");
                        JOptionPane.showMessageDialog(null, "Cliente em processamento Act!");
                    }
                }
            }

            tb.setRowCount(0);

            List<Objetos.ClientesOBJ> cliente = new Dados().Ativos();
            if (chekDes.isSelected()) {
                cliente = new Dados().Desativados();
            };

            for (Objetos.ClientesOBJ clientes : cliente) {
                String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                tb.addRow(dados);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnActDesActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        if (Tabela.getSelectedRow() != -1) {
            int id = Integer.parseInt(tb.getValueAt(Tabela.getSelectedRow(), 0).toString());
            RegistroDePagamento pag = new RegistroDePagamento();
            pag.setIdCliente(id);
            pag.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        if (Tabela.getSelectedRow() != -1) {
            int id = Integer.parseInt(tb.getValueAt(Tabela.getSelectedRow(), 0).toString());
            MesesPagos Mpagos = new MesesPagos();
            Mpagos.setIdCliente(id);
            Mpagos.setIdUsuario(idUsuario);
            Mpagos.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnPagamentosActionPerformed

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked
        // TODO add your handling code here
        txtPesquisa.setText("");
    }//GEN-LAST:event_txtPesquisaMouseClicked

    private int DP(int idCliente) {
        int Dia = -1;
        for (DiaPagamentoOBJ dia : Dias) {
            if (idCliente == dia.getId()) {
                Dia = dia.getDia();
            }
        }
        return Dia;
    }

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        modelo.setRowCount(0);
        if (chekAti.isSelected()) {
            List<ClientesOBJ> dados = new Dados().PesquisaClienteAtivos(txtPesquisa.getText());
            for (Objetos.ClientesOBJ clientes : dados) {
                String[] dado = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                modelo.addRow(dado);
            }
        } else if (chekDes.isSelected()) {
            List<ClientesOBJ> dados = new Dados().PesquisaClienteDesativados(txtPesquisa.getText());
            for (Objetos.ClientesOBJ clientes : dados) {
                String[] dado = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
                modelo.addRow(dado);
            }
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        if (chekAti.isSelected()) {
            new Dados().ImprimirActivados(new Dados().getNomeUsuário(getIdUsuario()));
        } else if (chekDes.isSelected()) {
            new Dados().ImprimirDesactivados(new Dados().getNomeUsuário(getIdUsuario()));
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void chekAtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekAtiActionPerformed
        // TODO add your handling code here:
        chekDes.setSelected(false);
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        tb.setRowCount(0);
        List<Objetos.ClientesOBJ> clientesActivados = new Dados().Ativos();
        for (Objetos.ClientesOBJ clientes : clientesActivados) {
            String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
            tb.addRow(dados);
        }

    }//GEN-LAST:event_chekAtiActionPerformed

    private void chekDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chekDesActionPerformed
        // TODO add your handling code here:
        chekAti.setSelected(false);
        DefaultTableModel tb = (DefaultTableModel) Tabela.getModel();
        tb.setRowCount(0);
        List<Objetos.ClientesOBJ> clientesDesactivados = new Dados().Desativados();
        for (Objetos.ClientesOBJ clientes : clientesDesactivados) {
            String[] dados = {Integer.toString(clientes.getId()), clientes.getNome(), "" + clientes.getDiaPagamento(), clientes.getInformação()};
            tb.addRow(dados);
        }
    }//GEN-LAST:event_chekDesActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Varredura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Varredura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Varredura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Varredura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Varredura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BI;
    private javax.swing.JTextField Contacto;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Endereço;
    private javax.swing.JTextField GPON;
    private javax.swing.JTextField Nacionalidade;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Serviço;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnActDes;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPagamentos;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbPacote;
    private javax.swing.JCheckBox chekAti;
    private javax.swing.JCheckBox chekDes;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextArea taNota;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField vlan;
    private javax.swing.JTextField whatsapp;
    // End of variables declaration//GEN-END:variables
}
