/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Objetos.Dados;
import Objetos.NotaDeDespesaOBJ;
import Objetos.TemaOBJ;
import Objetos.TipoDeDespesaOBJ;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Quingumba
 */
public class CaixaDespesas extends javax.swing.JFrame {

    /**
     * Creates new form FolhaDeSalario
     */
    private String previlegio, usuario;
    private int idUsuario;
    private Color CorBotao, CorLetra, CorFundo;
    List<TemaOBJ> tema = new ArrayList<>();

    public void SetCorBotoes(Color fundo, Color letra) {
        //COR DO FUNDO DO BOTAO

        btnAdd.setBackground(fundo);
        btnCancelar.setBackground(fundo);
        btnConfirmar.setBackground(fundo);
        txtBeneficiario.setBackground(fundo);
        txtValor.setBackground(fundo);
        cbTipo.setBackground(fundo);
        taDescrição.setBackground(fundo);

        //COR A LETRA
        btnAdd.setForeground(letra);
        btnCancelar.setForeground(letra);
        cbTipo.setForeground(letra);
        txtBeneficiario.setForeground(letra);
        taDescrição.setForeground(letra);
        btnConfirmar.setForeground(letra);
        txtValor.setForeground(letra);
    }

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
        if (CorFundo != new Color(0xfbfbfc)) {
            lbTitulo.setForeground(new Color(0xfbfbfc));
        }
    }

    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            btnAdd.setBackground(new Color(0x241f24));
            btnCancelar.setForeground(new Color(0xCC00CC));
            btnConfirmar.setBackground(new Color(0x241f24));
            taDescrição.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    List<TipoDeDespesaOBJ> despesa = new Dados().TiposDeDespesas();

    public CaixaDespesas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        // COLOCAR A JANELA NO CENTRO DO ECRÃ
        setLocationRelativeTo(null);
        //  COLOCAR OS CANTOS ARREDONDADOS AO ESTILO WINDOWS 11
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 10, 10));
        getRootPane().setBorder(BorderFactory.createLineBorder(new Color(204, 0, 204), 2));
        cbTipo.removeAllItems();
        for (TipoDeDespesaOBJ desp : despesa) {
            cbTipo.addItem(desp.getNome().toUpperCase());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtBeneficiario = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescrição = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(742, 379));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pFundo.setOpaque(false);
        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("VALOR: ");
        pFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("TIPO:");
        pFundo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 70, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("DESCRIÇÃO:");
        pFundo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 30));

        txtValor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtValor.setForeground(new java.awt.Color(204, 0, 204));
        txtValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        pFundo.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 40));

        txtBeneficiario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBeneficiario.setForeground(new java.awt.Color(204, 0, 204));
        txtBeneficiario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pFundo.add(txtBeneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 690, 40));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(204, 0, 204));
        lbTitulo.setText("NOTA DE DESPESA(CAIXA)");
        pFundo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 50));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 50, 40));

        pFundo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 880, 40));

        btnCancelar.setBackground(new java.awt.Color(241, 241, 241));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(204, 0, 204));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pFundo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 220, 50));

        btnConfirmar.setBackground(new java.awt.Color(241, 241, 241));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(204, 0, 204));
        btnConfirmar.setText("CONFIRMAR E IMPRIMIR");
        btnConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        pFundo.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 200, 50));

        cbTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbTipo.setForeground(new java.awt.Color(204, 0, 204));
        cbTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pFundo.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 370, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("BENEFICIÁRIO: ");
        pFundo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, 40));

        taDescrição.setForeground(new java.awt.Color(204, 0, 204));
        taDescrição.setLineWrap(true);
        taDescrição.setRows(5);
        taDescrição.setWrapStyleWord(true);
        taDescrição.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jScrollPane1.setViewportView(taDescrição);

        pFundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 690, 170));

        btnAdd.setBackground(new java.awt.Color(241, 241, 241));
        btnAdd.setForeground(new java.awt.Color(204, 0, 204));
        btnAdd.setText("+");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pFundo.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 40, 40));

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private int x, y;

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        NotaDeDespesaOBJ nota = new NotaDeDespesaOBJ(
                0,
                taDescrição.getText(),
                txtBeneficiario.getText(),
                new Dados().getIdDespesa(cbTipo.getSelectedItem().toString().toUpperCase()),
                txtValor.getText(),
                0,
                0,
                0,
                null
        );

        if (new Dados().RegistarDespesa(new Dados().getNomeUsuário(getIdUsuario()), nota)) {
            JOptionPane.showMessageDialog(null, "Despesa Registrada!");
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String cat = JOptionPane.showInputDialog(null, "INSIRA A CATEGORIA", "REGISTRO DE CATEGORIA", 1);

        if (new Dados().RegistrarTipoDeDespesa(new Dados().getNomeUsuário(getIdUsuario()), cat)) {
            cbTipo.removeAll();
            cbTipo.removeAllItems();
            despesa = new Dados().TiposDeDespesas();
            for (TipoDeDespesaOBJ desp : despesa) {
                cbTipo.addItem(desp.getNome().toUpperCase());
            }
            JOptionPane.showMessageDialog(null, "FEITO!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // TODO add your handling code here:
        char letra = evt.getKeyChar();
        if (!Character.isDigit(letra)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaixaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaixaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaixaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaixaDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaixaDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pFundo;
    private javax.swing.JTextArea taDescrição;
    private javax.swing.JTextField txtBeneficiario;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
