/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Objetos.Dados;
import Objetos.FechoDeContasOBJ;
import Objetos.SaidasPoDiaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quingumba
 */
public class FechoDeContas extends javax.swing.JFrame {

    /**
     * Creates new form FechoDeContas
     */
    private List<FechoDeContasOBJ> Entradas = new ArrayList<>();
    private List<FechoDeContasOBJ> Saidas = new ArrayList<>();
    private DefaultTableModel modelo, modelo2;
    private String previlegio2, usuario;
    private int idUsuario;
    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        lbFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        lbFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        lbFundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        lbFundo4.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            tbEntradaDiaria.setBackground(new Color(0x241f24));
            tbEntradaMensal.setBackground(new Color(0x241f24));
            tbSaidaDiaria.setBackground(new Color(0x241f24));
            tbSaidaMensal.setBackground(new Color(0x241f24));
            tbEntradaDiaria.setForeground(new Color(0xCC00CC));
            tbEntradaMensal.setForeground(new Color(0xCC00CC));
            tbSaidaDiaria.setForeground(new Color(0xCC00CC));
            tbSaidaMensal.setForeground(new Color(0xCC00CC));
            btnLimpar1.setBackground(new Color(0x241f24));
            btnLimpar2.setBackground(new Color(0x241f24));
            btnLimpar3.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getPrevilegio2() {
        return previlegio2;
    }

    public void setPrevilegio2(String previlegio) {
        this.previlegio2 = previlegio;
    }

    public FechoDeContas() {
        initComponents();
        modelo = (DefaultTableModel) tbEntradaMensal.getModel();
        modelo2 = (DefaultTableModel) tbSaidaMensal.getModel();
        Entradas = new Dados().EntradaPorMes();
        Saidas = new Dados().SaidasMensais();
        for (FechoDeContasOBJ fech : Entradas) {
            String[] dado = {fech.getAno() + "", fech.getMes(), fech.getEntrada() + ""};
            modelo.addRow(dado);
        }
        for (FechoDeContasOBJ saida : Saidas) {
            String[] dado = {saida.getAno() + "", saida.getMes(), saida.getSaida() + ""};
            modelo2.addRow(dado);
        }
        txtDeveEntrar.setText(new Dados().DeveriaEntrar() + " AOA");
        txtDeveEntrarAtivos.setText(new Dados().DeveriaEntrarAtivos() + " AOA");
        txtEstamosPerdendo.setText(new Dados().EstamosPerdendo() + " AOA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pEntrada = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtBusca3 = new javax.swing.JTextField();
        btnLimpar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEntradaMensal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEntradaDiaria = new javax.swing.JTable();
        lbFundo1 = new javax.swing.JLabel();
        pSaida = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtBusca4 = new javax.swing.JTextField();
        btnLimpar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSaidaMensal = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSaidaDiaria = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        lbFundo2 = new javax.swing.JLabel();
        pReceitas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        btnLimpar3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDeveEntrar = new javax.swing.JTextField();
        txtDeveEntrarAtivos = new javax.swing.JTextField();
        txtEstamosPerdendo = new javax.swing.JTextField();
        lbFundo3 = new javax.swing.JLabel();
        pRedimento = new javax.swing.JPanel();
        lbFundo4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jTabbedPane1.setForeground(new java.awt.Color(204, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        pEntrada.setBackground(new java.awt.Color(255, 255, 255));
        pEntrada.setOpaque(false);
        pEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "PESQUISA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusca3.setFont(new java.awt.Font("sansserif", 1, 21)); // NOI18N
        txtBusca3.setForeground(new java.awt.Color(204, 204, 204));
        txtBusca3.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtBusca3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusca3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusca3FocusLost(evt);
            }
        });
        txtBusca3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusca3KeyReleased(evt);
            }
        });
        jPanel6.add(txtBusca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 40));

        btnLimpar1.setBackground(new java.awt.Color(242, 242, 242));
        btnLimpar1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar1.setForeground(new java.awt.Color(204, 0, 204));
        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtro-limpo.png"))); // NOI18N
        btnLimpar1.setText("LIMPAR");
        btnLimpar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimpar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar1.setIconTextGap(20);
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 130, 40));

        pEntrada.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 964, 70));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tbEntradaMensal.setBackground(new java.awt.Color(215, 222, 230));
        tbEntradaMensal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tbEntradaMensal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tbEntradaMensal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ANO", "MÊS", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEntradaMensal.setOpaque(false);
        tbEntradaMensal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEntradaMensalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEntradaMensal);

        pEntrada.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, 385, 401));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tbEntradaDiaria.setBackground(new java.awt.Color(215, 222, 230));
        tbEntradaDiaria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tbEntradaDiaria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tbEntradaDiaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENTE", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEntradaDiaria.setOpaque(false);
        jScrollPane2.setViewportView(tbEntradaDiaria);
        if (tbEntradaDiaria.getColumnModel().getColumnCount() > 0) {
            tbEntradaDiaria.getColumnModel().getColumn(1).setMinWidth(200);
            tbEntradaDiaria.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbEntradaDiaria.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        pEntrada.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 94, 567, 401));

        lbFundo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pEntrada.add(lbFundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        jTabbedPane1.addTab("ENTRADAS", pEntrada);

        pSaida.setBackground(new java.awt.Color(255, 255, 255));
        pSaida.setOpaque(false);
        pSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pSaidaFocusGained(evt);
            }
        });
        pSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSaidaMouseClicked(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "PESQUISA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusca4.setFont(new java.awt.Font("sansserif", 1, 21)); // NOI18N
        txtBusca4.setForeground(new java.awt.Color(204, 204, 204));
        txtBusca4.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtBusca4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusca4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusca4FocusLost(evt);
            }
        });
        txtBusca4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusca4KeyReleased(evt);
            }
        });
        jPanel7.add(txtBusca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 40));

        btnLimpar2.setBackground(new java.awt.Color(242, 242, 242));
        btnLimpar2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar2.setForeground(new java.awt.Color(204, 0, 204));
        btnLimpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtro-limpo.png"))); // NOI18N
        btnLimpar2.setText("LIMPAR");
        btnLimpar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimpar2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar2.setIconTextGap(20);
        btnLimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnLimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 130, 40));

        jScrollPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tbSaidaMensal.setBackground(new java.awt.Color(215, 222, 230));
        tbSaidaMensal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tbSaidaMensal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tbSaidaMensal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ANO", "MÊS", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSaidaMensal.setOpaque(false);
        tbSaidaMensal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSaidaMensalMouseClicked(evt);
            }
        });
        tbSaidaMensal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbSaidaMensalPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tbSaidaMensal);

        jScrollPane4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tbSaidaDiaria.setBackground(new java.awt.Color(215, 222, 230));
        tbSaidaDiaria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tbSaidaDiaria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tbSaidaDiaria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VALOR", "DIA", "HORA", "BENEFICIADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSaidaDiaria.setOpaque(false);
        jScrollPane4.setViewportView(tbSaidaDiaria);
        if (tbSaidaDiaria.getColumnModel().getColumnCount() > 0) {
            tbSaidaDiaria.getColumnModel().getColumn(0).setMinWidth(150);
            tbSaidaDiaria.getColumnModel().getColumn(0).setPreferredWidth(150);
            tbSaidaDiaria.getColumnModel().getColumn(0).setMaxWidth(150);
            tbSaidaDiaria.getColumnModel().getColumn(1).setMinWidth(80);
            tbSaidaDiaria.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbSaidaDiaria.getColumnModel().getColumn(1).setMaxWidth(80);
            tbSaidaDiaria.getColumnModel().getColumn(2).setMinWidth(150);
            tbSaidaDiaria.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbSaidaDiaria.getColumnModel().getColumn(2).setMaxWidth(150);
            tbSaidaDiaria.getColumnModel().getColumn(3).setMinWidth(200);
            tbSaidaDiaria.getColumnModel().getColumn(3).setPreferredWidth(200);
            tbSaidaDiaria.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jTextArea1.setOpaque(false);
        jScrollPane5.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("DESCRIÇÃO DA SAÍDA");

        lbFundo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        javax.swing.GroupLayout pSaidaLayout = new javax.swing.GroupLayout(pSaida);
        pSaida.setLayout(pSaidaLayout);
        pSaidaLayout.setHorizontalGroup(
            pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                    .addGroup(pSaidaLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pSaidaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pSaidaLayout.setVerticalGroup(
            pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pSaidaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pSaidaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("SAIDAS", pSaida);

        pReceitas.setBackground(new java.awt.Color(255, 255, 255));
        pReceitas.setOpaque(false);
        pReceitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "PESQUISA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusca.setFont(new java.awt.Font("sansserif", 1, 21)); // NOI18N
        txtBusca.setForeground(new java.awt.Color(204, 204, 204));
        txtBusca.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscaFocusLost(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });
        jPanel2.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 40));

        btnLimpar3.setBackground(new java.awt.Color(242, 242, 242));
        btnLimpar3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar3.setForeground(new java.awt.Color(204, 0, 204));
        btnLimpar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtro-limpo.png"))); // NOI18N
        btnLimpar3.setText("LIMPAR");
        btnLimpar3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimpar3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar3.setIconTextGap(20);
        btnLimpar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 130, 40));

        pReceitas.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 960, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("O QUE DEVERIA ENTRAR POR MÊS");
        pReceitas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("O QUE DEVERIA ENTRAR PELOS ACTIVOS");
        pReceitas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 300, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("O QUE PERDEMOS PELOS DESACTIVADOS");
        pReceitas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 90, 290, 30));

        txtDeveEntrar.setEditable(false);
        txtDeveEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDeveEntrar.setForeground(new java.awt.Color(204, 0, 204));
        txtDeveEntrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDeveEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pReceitas.add(txtDeveEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 280, 30));

        txtDeveEntrarAtivos.setEditable(false);
        txtDeveEntrarAtivos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDeveEntrarAtivos.setForeground(new java.awt.Color(204, 0, 204));
        txtDeveEntrarAtivos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDeveEntrarAtivos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pReceitas.add(txtDeveEntrarAtivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 280, 30));

        txtEstamosPerdendo.setEditable(false);
        txtEstamosPerdendo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEstamosPerdendo.setForeground(new java.awt.Color(204, 0, 204));
        txtEstamosPerdendo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEstamosPerdendo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pReceitas.add(txtEstamosPerdendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 280, 30));

        lbFundo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        pReceitas.add(lbFundo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        jTabbedPane1.addTab("RECEITAS", pReceitas);

        pRedimento.setBackground(new java.awt.Color(255, 255, 255));
        pRedimento.setOpaque(false);

        lbFundo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        javax.swing.GroupLayout pRedimentoLayout = new javax.swing.GroupLayout(pRedimento);
        pRedimento.setLayout(pRedimentoLayout);
        pRedimentoLayout.setHorizontalGroup(
            pRedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(pRedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pRedimentoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbFundo4, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pRedimentoLayout.setVerticalGroup(
            pRedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(pRedimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pRedimentoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lbFundo4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("RENDIMENTO", pRedimento);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 980, 540));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 970, 40));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("FECHO DE CONTAS");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 39));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        lbFundo.setMaximumSize(new java.awt.Dimension(810, 690));
        lbFundo.setMinimumSize(new java.awt.Dimension(810, 690));
        lbFundo.setPreferredSize(new java.awt.Dimension(810, 690));
        jPanel1.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private int x, y;

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnLimpar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar3ActionPerformed
        // TODO add your handling code here:
        txtBusca.setText("");
    }//GEN-LAST:event_btnLimpar3ActionPerformed

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        String texto = txtBusca.getText();

    }//GEN-LAST:event_txtBuscaKeyReleased

    private void txtBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaFocusLost
        // TODO add your handling code here:
        txtBusca.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtBuscaFocusLost

    private void txtBuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaFocusGained
        // TODO add your handling code here:
        txtBusca.setForeground(new Color(0xCC00CC));
        txtBusca.setText("");
    }//GEN-LAST:event_txtBuscaFocusGained

    private void btnLimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar2ActionPerformed

    private void txtBusca4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusca4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusca4KeyReleased

    private void txtBusca4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusca4FocusLost
        // TODO add your handling code here:
        txtBusca4.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca4.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtBusca4FocusLost

    private void txtBusca4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusca4FocusGained
        // TODO add your handling code here:
        txtBusca4.setForeground(new Color(0xCC00CC));
        txtBusca4.setText("");
    }//GEN-LAST:event_txtBusca4FocusGained

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void txtBusca3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusca3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusca3KeyReleased

    private void txtBusca3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusca3FocusLost
        // TODO add your handling code here:
        txtBusca3.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca3.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtBusca3FocusLost

    private void txtBusca3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusca3FocusGained
        // TODO add your handling code here:
        txtBusca3.setForeground(new Color(0xCC00CC));
        txtBusca3.setText("");
    }//GEN-LAST:event_txtBusca3FocusGained

    private void tbEntradaMensalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEntradaMensalMouseClicked
        // TODO add your handling code here:
        int linha = tbEntradaMensal.getSelectedRow();
        modelo = (DefaultTableModel) tbEntradaMensal.getModel();
        if (linha != -1) {
            String Mes = modelo.getValueAt(linha, 1).toString();
            String ano = modelo.getValueAt(linha, 0).toString();
            List<FechoDeContasOBJ> f = new Dados().EntradaPorMesEspecifico(Mes, Integer.parseInt(ano));
            modelo = (DefaultTableModel) tbEntradaDiaria.getModel();
            modelo.setRowCount(0);
            for (FechoDeContasOBJ fe : f) {
                String[] val = {fe.getMes(), fe.getEntrada() + ""};
                modelo.addRow(val);
            }
        }
    }//GEN-LAST:event_tbEntradaMensalMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void pSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSaidaMouseClicked
        // TODO add your handling code here:
        modelo2 = (DefaultTableModel) tbSaidaMensal.getModel();
        Saidas = new Dados().SaidasMensais();
        if (!Saidas.isEmpty() || Saidas != null) {
            for (FechoDeContasOBJ Saida : Saidas) {
                String[] dado = {Saida.getAno() + "", Saida.getMes(), Saida.getSaida() + ""};
                modelo2.addRow(dado);
            }
        }
    }//GEN-LAST:event_pSaidaMouseClicked

    private void tbSaidaMensalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbSaidaMensalPropertyChange
        // TODO add your handling code here:
        int linha = tbEntradaMensal.getSelectedRow();
        modelo = (DefaultTableModel) tbEntradaMensal.getModel();
        if (linha != -1) {
            String Mes = modelo.getValueAt(linha, 1).toString();
            String ano = modelo.getValueAt(linha, 0).toString();
            List<FechoDeContasOBJ> f = new Dados().EntradaPorMesEspecifico(Mes, Integer.parseInt(ano));
            modelo = (DefaultTableModel) tbEntradaDiaria.getModel();
            modelo.setRowCount(0);
            for (FechoDeContasOBJ fe : f) {
                String[] val = {fe.getMes(), fe.getEntrada() + ""};
                modelo.addRow(val);
            }
        }
    }//GEN-LAST:event_tbSaidaMensalPropertyChange

    private void pSaidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pSaidaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pSaidaFocusGained

    private void tbSaidaMensalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSaidaMensalMouseClicked
        // TODO add your handling code here:
        modelo2 = (DefaultTableModel) tbSaidaMensal.getModel();
        int linha = tbSaidaMensal.getSelectedRow();
        if (linha != -1) {
            int idMes = new Dados().idMes(modelo2.getValueAt(linha, 1).toString());
            int ano = Integer.parseInt(modelo2.getValueAt(linha, 0).toString());
            List<SaidasPoDiaOBJ> sdia = new Dados().SaidasPorDia(idMes, ano);
            modelo2 = (DefaultTableModel) tbSaidaDiaria.getModel();
            modelo2.setRowCount(0);
            for (SaidasPoDiaOBJ saida : sdia) {
                String[] dado = {saida.getValor() + "", saida.getDia() + "", saida.getHora(), saida.getBeneficiario()};
                modelo2.addRow(dado);
            }
        }
    }//GEN-LAST:event_tbSaidaMensalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FechoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FechoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FechoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FechoDeContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FechoDeContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JButton btnLimpar3;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbFundo1;
    private javax.swing.JLabel lbFundo2;
    private javax.swing.JLabel lbFundo3;
    private javax.swing.JLabel lbFundo4;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pEntrada;
    private javax.swing.JPanel pReceitas;
    private javax.swing.JPanel pRedimento;
    private javax.swing.JPanel pSaida;
    private javax.swing.JTable tbEntradaDiaria;
    private javax.swing.JTable tbEntradaMensal;
    private javax.swing.JTable tbSaidaDiaria;
    private javax.swing.JTable tbSaidaMensal;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtBusca3;
    private javax.swing.JTextField txtBusca4;
    private javax.swing.JTextField txtDeveEntrar;
    private javax.swing.JTextField txtDeveEntrarAtivos;
    private javax.swing.JTextField txtEstamosPerdendo;
    // End of variables declaration//GEN-END:variables
}
