/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Janelas.Equipamentos;
import Janelas.HistoricoGlobal;
import Janelas.HistóricoAD;
import Objetos.Dados;
import Objetos.TemaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Custodio Quingumba
 */
public class GerenciarADM extends javax.swing.JFrame {

    private int idUsuario;
    private String previlegio, usuario;
    private int idTema;
    private Color CorBotao, CorLetra, CorFundo;
    List<TemaOBJ> tema = new ArrayList<>();

    public void SetCorBotoes(Color fundo, Color letra) {
        //COR DO FUNDO DO BOTAO
        pFundo.setBackground(fundo);
        btDespesas.setBackground(fundo);
        btFolha.setBackground(fundo);
        btHistorico.setBackground(fundo);
        btHistoricoGeral.setBackground(fundo);
        btStoque.setBackground(fundo);

        //COR A LETRA
        btDespesas.setForeground(letra);
        btFolha.setForeground(letra);
        btHistorico.setForeground(letra);
        btHistoricoGeral.setForeground(letra);
        btStoque.setForeground(letra);
    }

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
    }

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }

    public String getPrevilegio() {
        return previlegio;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
        if (new Dados().getNomeUsuário(idUsuario).equalsIgnoreCase("Arthur Da Cunha")) {
            btHistorico.setEnabled(true);
        }
    }

    /**
     * Creates new form ClientesOuEquipamento
     */
    public GerenciarADM() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
    }

    public void setPrevilegio(String previlegio) {
        this.previlegio = previlegio;
        if (getPrevilegio().equalsIgnoreCase("F")) {
            btHistorico.setEnabled(true);
            btHistoricoGeral.setEnabled(true);
            btStoque.setEnabled(true);
            btFolha.setEnabled(true);
        } else if (getPrevilegio().equalsIgnoreCase("T")) {
            btHistorico.setEnabled(false);
            btStoque.setEnabled(false);
            btHistoricoGeral.setEnabled(false);
            btFolha.setEnabled(false);
        } else if (getPrevilegio().equalsIgnoreCase("V")) {
            btStoque.setEnabled(true);
            btHistorico.setEnabled(false);
            btHistoricoGeral.setEnabled(false);
            btFolha.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        btStoque = new javax.swing.JButton();
        btHistorico = new javax.swing.JButton();
        btHistoricoGeral = new javax.swing.JButton();
        btFolha = new javax.swing.JButton();
        btDespesas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIAR");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(295, 140));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setOpaque(false);
        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btStoque.setBackground(new java.awt.Color(241, 241, 241));
        btStoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btStoque.setForeground(new java.awt.Color(204, 0, 204));
        btStoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inventario.png"))); // NOI18N
        btStoque.setText("STOQUE");
        btStoque.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btStoque.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btStoque.setIconTextGap(20);
        btStoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStoqueActionPerformed(evt);
            }
        });
        pFundo.add(btStoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 150, 50));

        btHistorico.setBackground(new java.awt.Color(241, 241, 241));
        btHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHistorico.setForeground(new java.awt.Color(204, 0, 204));
        btHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/historia.png"))); // NOI18N
        btHistorico.setText("HISTÓRICO");
        btHistorico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btHistorico.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btHistorico.setIconTextGap(10);
        btHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoActionPerformed(evt);
            }
        });
        pFundo.add(btHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        btHistoricoGeral.setBackground(new java.awt.Color(241, 241, 241));
        btHistoricoGeral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHistoricoGeral.setForeground(new java.awt.Color(204, 0, 204));
        btHistoricoGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/historia.png"))); // NOI18N
        btHistoricoGeral.setText("HISTÓRICO GERAL");
        btHistoricoGeral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btHistoricoGeral.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btHistoricoGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistoricoGeralActionPerformed(evt);
            }
        });
        pFundo.add(btHistoricoGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 150, 50));

        btFolha.setBackground(new java.awt.Color(241, 241, 241));
        btFolha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFolha.setForeground(new java.awt.Color(204, 0, 204));
        btFolha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inventario.png"))); // NOI18N
        btFolha.setText("FOLHA SALARIAL");
        btFolha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btFolha.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btFolha.setIconTextGap(20);
        btFolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFolhaActionPerformed(evt);
            }
        });
        pFundo.add(btFolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 160, 50));

        btDespesas.setBackground(new java.awt.Color(241, 241, 241));
        btDespesas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDespesas.setForeground(new java.awt.Color(204, 0, 204));
        btDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/inventario.png"))); // NOI18N
        btDespesas.setText("DESPESAS");
        btDespesas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btDespesas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btDespesas.setIconTextGap(20);
        btDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDespesasActionPerformed(evt);
            }
        });
        pFundo.add(btDespesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 130, 50));

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        setSize(new java.awt.Dimension(816, 79));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btStoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStoqueActionPerformed
        // TODO add your handling code here:
        Equipamentos eq = new Equipamentos();
        eq.setIdUsuario(getIdUsuario());
        eq.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btStoqueActionPerformed

    private void btHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoActionPerformed
        // TODO add your handling code here:
        new HistóricoAD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHistoricoActionPerformed

    private void btHistoricoGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistoricoGeralActionPerformed
        // TODO add your handling code here:
        new HistoricoGlobal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHistoricoGeralActionPerformed

    private void btFolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFolhaActionPerformed
        // TODO add your handling code here:
        TodaFolhasSalariais tdFolha = new TodaFolhasSalariais();
        tdFolha.setIdUsuario(idUsuario);
        tdFolha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btFolhaActionPerformed

    private void btDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDespesasActionPerformed
        // TODO add your handling code here:
        TodasFolhasDespesas tfd = new TodasFolhasDespesas();
        tfd.setIdUsuario(idUsuario);
        tfd.setPrevilegio2(previlegio);
        this.dispose();
        tfd.setVisible(true);
    }//GEN-LAST:event_btDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDespesas;
    private javax.swing.JButton btFolha;
    private javax.swing.JButton btHistorico;
    private javax.swing.JButton btHistoricoGeral;
    private javax.swing.JButton btStoque;
    private javax.swing.JPanel pFundo;
    // End of variables declaration//GEN-END:variables
}
