/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Janelas.NovoUsuario;
import Objetos.Dados;
import Objetos.FolhaOBJ;
import Objetos.LoginOBJ;
import Objetos.MesesOBJ;
import Objetos.SalarioOBJ;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quingumba
 */
public class NovaFolhaSalarial extends javax.swing.JFrame {

    /**
     * Creates new form NovaFolhaSalarial
     */
    private String previlegio2, usuario;
    private int idUsuario;

    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            tabela.setBackground(new Color(0x241f24));
            tabela.setForeground(new Color(0xCC00CC));
            btnLimpar.setBackground(new Color(0x241f24));
            btnAdicionar.setBackground(new Color(0x241f24));
            btnNovoFuncionario.setBackground(new Color(0x241f24));
            btnRemover.setBackground(new Color(0x241f24));
            BtnImprimir.setBackground(new Color(0x241f24));
            cbFuncionarios.setBackground(new Color(0x241f24));
            cbMeses.setBackground(new Color(0x241f24));
            btnVoltar.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getPrevilegio2() {
        return previlegio2;
    }

    public void setPrevilegio2(String previlegio) {
        this.previlegio2 = previlegio;
    }

    private List<LoginOBJ> logins = new Dados().ObterUsuários();
    private List<MesesOBJ> meses = new Dados().TodosMeses();

    public NovaFolhaSalarial() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        for (LoginOBJ login : logins) {
            cbFuncionarios.addItem(login.getNome().toUpperCase());
        }
        for (MesesOBJ Mes : meses) {
            cbMeses.addItem(Mes.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        cbFuncionarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNovoFuncionario = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        cbMeses = new javax.swing.JComboBox<>();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRAR FOLHA SALARIAL");
        setMinimumSize(new java.awt.Dimension(1100, 640));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 1070, 40));

        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("NOME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 78, 30));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("FOLHA SALARIAL");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 39));

        cbFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbFuncionarios.setForeground(new java.awt.Color(204, 0, 204));
        cbFuncionarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel1.add(cbFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 570, 30));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tabela.setBackground(new java.awt.Color(215, 222, 230));
        tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tabela.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "FUNÇÃO", "SALÁRIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(2).setMinWidth(150);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 800, 480));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "ACÕES"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNovoFuncionario.setBackground(new java.awt.Color(242, 242, 242));
        btnNovoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNovoFuncionario.setForeground(new java.awt.Color(204, 0, 204));
        btnNovoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnNovoFuncionario.setText("NOVA FUNCIONÁRIO");
        btnNovoFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnNovoFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNovoFuncionario.setIconTextGap(10);
        btnNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoFuncionarioActionPerformed(evt);
            }
        });
        jPanel3.add(btnNovoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 50));

        btnRemover.setBackground(new java.awt.Color(242, 242, 242));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(204, 0, 204));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/botao-apagar.png"))); // NOI18N
        btnRemover.setText("REMOVER");
        btnRemover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRemover.setIconTextGap(40);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 50));

        btnLimpar.setBackground(new java.awt.Color(242, 242, 242));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(204, 0, 204));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnLimpar.setText("LIMPAR LISTA");
        btnLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar.setIconTextGap(20);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 50));

        BtnImprimir.setBackground(new java.awt.Color(242, 242, 242));
        BtnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnImprimir.setForeground(new java.awt.Color(204, 0, 204));
        BtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/imprimir.png"))); // NOI18N
        BtnImprimir.setText("SALVAR FOLHA");
        BtnImprimir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        BtnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnImprimir.setIconTextGap(20);
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        jPanel3.add(BtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 50));

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setIconTextGap(40);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, 50));

        btnAdicionar.setBackground(new java.awt.Color(242, 242, 242));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(204, 0, 204));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/finalizado.png"))); // NOI18N
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAdicionar.setIconTextGap(40);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 50));

        cbMeses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbMeses.setForeground(new java.awt.Color(204, 0, 204));
        cbMeses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel3.add(cbMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 230, 480));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        lbFundo.setMaximumSize(new java.awt.Dimension(810, 690));
        lbFundo.setMinimumSize(new java.awt.Dimension(810, 690));
        lbFundo.setPreferredSize(new java.awt.Dimension(810, 690));
        jPanel1.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int x, y;

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) tabela.getModel();
        boolean tem = false;

        for (int i = 0; i < tabela.getRowCount(); i++) {
            if (tb.getValueAt(i, 0).toString().equalsIgnoreCase(cbFuncionarios.getSelectedItem().toString())) {
                tem = true;
                break;
            }
        }

        if (!tem) {
            String funcionario = cbFuncionarios.getSelectedItem().toString();
            LoginOBJ func = new LoginOBJ();

            for (LoginOBJ login : logins) {
                if (login.getNome().equalsIgnoreCase(cbFuncionarios.getSelectedItem().toString())) {
                    func = login;
                }
            }
            int idCat = new Dados().getIdCategoria(func.getCategoria());

            String salarString = new Dados().getValorSalario(idCat);
            Object dado[] = {funcionario, func.getCategoria(), salarString};
            tb.addRow(dado);
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário já adicionado");
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFuncionarioActionPerformed
        // TODO add your handling code here:
        NovoUsuario nu = new NovoUsuario();
        nu.setIdUsuario(idUsuario);
        nu.setIdTema(idTema);
        nu.setVisible(true);
        logins = new Dados().ObterUsuários();
        cbFuncionarios.removeAllItems();
        for (LoginOBJ login : logins) {
            cbFuncionarios.addItem(login.getNome());
        }
    }//GEN-LAST:event_btnNovoFuncionarioActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) tabela.getModel();
        if (tabela.getSelectedRow() != -1) {
            int linha = tabela.getSelectedRow();
            tb.removeRow(linha);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) tabela.getModel();

        if (tb.getRowCount() > 0) {
            String ano = "" + new Dados().AnoServidor();
            boolean posso = false;
            for (int i = 0; i < tb.getRowCount(); i++) {
                String nome = tb.getValueAt(i, 0).toString();
                String função = tb.getValueAt(i, 1).toString();
                int idSalario = new Dados().getIdCategoria(função);
                FolhaOBJ folha = new FolhaOBJ(0, nome, idSalario, cbMeses.getSelectedIndex() + 1, ano);
                posso = new Dados().ConfirmaFolha(folha) == 0;
            }

            if (posso) {
                for (int i = 0; i < tb.getRowCount(); i++) {
                    String nome = tb.getValueAt(i, 0).toString();
                    String função = tb.getValueAt(i, 1).toString();
                    int idSalario = new Dados().getIdCategoria(função);
                    FolhaOBJ folha = new FolhaOBJ(0, nome, idSalario, cbMeses.getSelectedIndex() + 1, ano);
                    new Dados().RegistrarFolhaDeSalario(new Dados().getNomeUsuário(getIdUsuario()), folha);
                }
                int op = JOptionPane.showConfirmDialog(null, "Folha Criada, Imprimir?");
                if (op == 0) {
                    JOptionPane.showMessageDialog(null, "Sim");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Folha já existe");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Folha Vazia");
        }
    }//GEN-LAST:event_BtnImprimirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) tabela.getModel();
        tb.setRowCount(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaFolhaSalarial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaFolhaSalarial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaFolhaSalarial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaFolhaSalarial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaFolhaSalarial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnNovoFuncionario;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbFuncionarios;
    private javax.swing.JComboBox<String> cbMeses;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
