/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Janelas.*;
import Objetos.TemaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Quingumba
 */
public class NovoADM extends javax.swing.JFrame {

    /**
     * Creates new form NovoOp
     */
    private String previlegio, usuario;
    private int idUsuario;
    private int idTema;
    private Color CorBotao, CorLetra, CorFundo;
    List<TemaOBJ> tema = new ArrayList<>();

    public void SetCorBotoes(Color fundo, Color letra) {
        //COR DO FUNDO DO BOTAO
        pFundo.setBackground(fundo);
        btClientes.setBackground(fundo);
        btFolhaSalarial.setBackground(fundo);
        btFornecedor.setBackground(fundo);
        btNotaDeDespesa.setBackground(fundo);

        //COR A LETRA
        btClientes.setForeground(letra);
        btFolhaSalarial.setForeground(letra);
        btFornecedor.setForeground(letra);
        btNotaDeDespesa.setForeground(letra);
    }

    public Color getCorBotao() {
        return CorBotao;
    }

    public void setCorBotao(Color CorBotao) {
        this.CorBotao = CorBotao;
    }

    public Color getCorLetra() {
        return CorLetra;
    }

    public void setCorLetra(Color CorLetra) {
        this.CorLetra = CorLetra;
    }

    public Color getCorFundo() {
        return CorFundo;
    }

    public void setCorFundo(Color CorFundo) {
        this.CorFundo = CorFundo;
        pFundo.setBackground(CorFundo);
    }

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getPrevilegio() {
        return previlegio;
    }

    public void setPrevilegio(String previlegio) {
        this.previlegio = previlegio;
        if (this.previlegio.equalsIgnoreCase("R") || this.previlegio.equalsIgnoreCase("D")) {
            btFolhaSalarial.setEnabled(true);
        } else {
            btFolhaSalarial.setEnabled(false);
        }
        if (this.previlegio.equalsIgnoreCase("V") || this.previlegio.equalsIgnoreCase("D")) {
            btNotaDeDespesa.setEnabled(true);
        } else {
            btNotaDeDespesa.setEnabled(false);
        }
    }

    public NovoADM() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        btClientes = new javax.swing.JButton();
        btFornecedor = new javax.swing.JButton();
        btFolhaSalarial = new javax.swing.JButton();
        btNotaDeDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NOVO");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(347, 90));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btClientes.setBackground(new java.awt.Color(241, 241, 241));
        btClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btClientes.setForeground(new java.awt.Color(204, 0, 204));
        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/adicionar-cliente.png"))); // NOI18N
        btClientes.setText("CLIENTE");
        btClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btClientes.setIconTextGap(10);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        pFundo.add(btClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        btFornecedor.setBackground(new java.awt.Color(241, 241, 241));
        btFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFornecedor.setForeground(new java.awt.Color(204, 0, 204));
        btFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/entregador.png"))); // NOI18N
        btFornecedor.setText("FORNECEDOR");
        btFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btFornecedor.setIconTextGap(10);
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });
        pFundo.add(btFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, 50));

        btFolhaSalarial.setBackground(new java.awt.Color(241, 241, 241));
        btFolhaSalarial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btFolhaSalarial.setForeground(new java.awt.Color(204, 0, 204));
        btFolhaSalarial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salario.png"))); // NOI18N
        btFolhaSalarial.setText("FOLHA SALARIAL");
        btFolhaSalarial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btFolhaSalarial.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btFolhaSalarial.setIconTextGap(10);
        btFolhaSalarial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFolhaSalarialActionPerformed(evt);
            }
        });
        pFundo.add(btFolhaSalarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 170, 50));

        btNotaDeDespesa.setBackground(new java.awt.Color(241, 241, 241));
        btNotaDeDespesa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btNotaDeDespesa.setForeground(new java.awt.Color(204, 0, 204));
        btNotaDeDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/salario.png"))); // NOI18N
        btNotaDeDespesa.setText("NOTA DE DESPESA");
        btNotaDeDespesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btNotaDeDespesa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btNotaDeDespesa.setIconTextGap(10);
        btNotaDeDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNotaDeDespesaActionPerformed(evt);
            }
        });
        pFundo.add(btNotaDeDespesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 170, 50));

        getContentPane().add(pFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        // TODO add your handling code here:
        NovoCliente novo = new NovoCliente();
        novo.setIdUsuario(idUsuario);
        novo.setIdTema(idTema);
        novo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btClientesActionPerformed

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        // TODO add your handling code here:
        Fornecedores fornecedor = new Fornecedores();
        fornecedor.setIdUsuario(getIdUsuario());
        fornecedor.setIdTema(idTema);
        fornecedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btFolhaSalarialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFolhaSalarialActionPerformed
        // TODO add your handling code here:
        NovaFolhaSalarial folha = new NovaFolhaSalarial();
        folha.setIdUsuario(getIdUsuario());
        folha.setIdTema(idTema);
        folha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btFolhaSalarialActionPerformed

    private void btNotaDeDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNotaDeDespesaActionPerformed
        // TODO add your handling code here:
        CaixaDespesas cxa = new CaixaDespesas();
        cxa.setIdUsuario(getIdUsuario());
        cxa.setIdTema(idTema);
        cxa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btNotaDeDespesaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btFolhaSalarial;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btNotaDeDespesa;
    private javax.swing.JPanel pFundo;
    // End of variables declaration//GEN-END:variables
}
