/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Objetos.Dados;
import Objetos.FolhaExtensaOBJ;
import Objetos.FolhaOBJ;
import Objetos.MesesOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quingumba
 */
public class TodaFolhasSalariais extends javax.swing.JFrame {

    private String previlegio2, usuario;
    private int idUsuario;
    DefaultTableModel modelo;
    List<FolhaExtensaOBJ> folhaExtensa = new ArrayList<>();
    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            tabela.setBackground(new Color(0x241f24));
            tabela.setForeground(new Color(0xCC00CC));
            btnAddCategoria.setBackground(new Color(0x241f24));
            btnVoltar.setBackground(new Color(0x241f24));
            btnRemover.setBackground(new Color(0x241f24));
            btnLimpar.setBackground(new Color(0x241f24));
            btnImprimir.setBackground(new Color(0x241f24));
            btnFinalizar.setBackground(new Color(0x241f24));
            cbFolhas.setBackground(new Color(0x241f24));
            cbMeses.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0xCC00CC));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getPrevilegio2() {
        return previlegio2;
    }

    public void setPrevilegio2(String previlegio) {
        this.previlegio2 = previlegio;
    }

    /**
     * Creates new form TodaFolhasSalariais
     */
    public TodaFolhasSalariais() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Icones/figicon.png")).getImage());
        List<FolhaOBJ> f = new Dados().FolhasAno();
        List<MesesOBJ> meses;

        if (f != null) {
            for (FolhaOBJ folha : f) {
                boolean tem = false;
                if (cbFolhas.getItemCount() < 1) {
                    cbFolhas.addItem(folha.getAno());
                }
                for (int i = 0; i <= cbFolhas.getItemCount(); i++) {
                    tem = folha.getAno().equalsIgnoreCase(cbFolhas.getItemAt(i));
                }
                if (tem) {

                }
            }
            meses = new Dados().FolhasMeses(Integer.parseInt((cbFolhas.getSelectedItem().toString())));
            for (MesesOBJ Mes : meses) {
                cbMeses.addItem(Mes.getNome());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbFolhas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAddCategoria = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        cbMeses = new javax.swing.JComboBox<>();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FOLHAS SALARIAIS REGISTRADAS");
        setMaximumSize(new java.awt.Dimension(1100, 642));
        setMinimumSize(new java.awt.Dimension(1100, 642));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 1070, 40));

        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("ANO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("FOLHAS SALARIAIS REGISTRADAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 39));

        cbFolhas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbFolhas.setForeground(new java.awt.Color(204, 0, 204));
        cbFolhas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jPanel1.add(cbFolhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 320, 30));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tabela.setBackground(new java.awt.Color(215, 222, 230));
        tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tabela.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "SALÁRIO", "IRT", "INSS", "SUBS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(1).setMinWidth(150);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(1).setMaxWidth(150);
            tabela.getColumnModel().getColumn(2).setMinWidth(100);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(2).setMaxWidth(100);
            tabela.getColumnModel().getColumn(3).setMinWidth(100);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(3).setMaxWidth(100);
            tabela.getColumnModel().getColumn(4).setMinWidth(100);
            tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 800, 480));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "ACÕES"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCategoria.setBackground(new java.awt.Color(242, 242, 242));
        btnAddCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCategoria.setForeground(new java.awt.Color(204, 0, 204));
        btnAddCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnAddCategoria.setText("NOVA CATEGORIA");
        btnAddCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnAddCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAddCategoria.setIconTextGap(10);
        btnAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 50));

        btnRemover.setBackground(new java.awt.Color(242, 242, 242));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(204, 0, 204));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/botao-apagar.png"))); // NOI18N
        btnRemover.setText("REMOVER");
        btnRemover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRemover.setIconTextGap(40);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 50));

        btnLimpar.setBackground(new java.awt.Color(242, 242, 242));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(204, 0, 204));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnLimpar.setText("LIMPAR LISTA");
        btnLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar.setIconTextGap(20);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 50));

        btnImprimir.setBackground(new java.awt.Color(242, 242, 242));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(204, 0, 204));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/imprimir.png"))); // NOI18N
        btnImprimir.setText("SALVAR FOLHA");
        btnImprimir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnImprimir.setIconTextGap(20);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel3.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 50));

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setIconTextGap(40);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, 50));

        btnFinalizar.setBackground(new java.awt.Color(242, 242, 242));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(204, 0, 204));
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/finalizado.png"))); // NOI18N
        btnFinalizar.setText("ADICIONAR");
        btnFinalizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnFinalizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFinalizar.setIconTextGap(40);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 50));

        cbMeses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbMeses.setForeground(new java.awt.Color(204, 0, 204));
        cbMeses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        cbMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMesesItemStateChanged(evt);
            }
        });
        cbMeses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMesesMouseClicked(evt);
            }
        });
        jPanel3.add(cbMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 230, 480));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        lbFundo.setMaximumSize(new java.awt.Dimension(810, 690));
        lbFundo.setMinimumSize(new java.awt.Dimension(810, 690));
        lbFundo.setPreferredSize(new java.awt.Dimension(810, 690));
        jPanel1.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private int x, y;

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoriaActionPerformed

    }//GEN-LAST:event_btnAddCategoriaActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        NovaFolhaSalarial f = new NovaFolhaSalarial();
        f.setIdUsuario(idUsuario);
        f.setPrevilegio2(previlegio2);
        this.dispose();
        f.setVisible(true);

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void cbMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMesesItemStateChanged
        // TODO add your handling code here:
        folhaExtensa = new Dados().FolhasAgora(cbFolhas.getSelectedItem().toString(), new Dados().idMes(cbMeses.getSelectedItem().toString()) + "");
        modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (FolhaExtensaOBJ fe : folhaExtensa) {
            String dado[] = {fe.getFuncionario(), fe.getSalario(), fe.getIRT(), fe.getINSS(), fe.getSubsidio()};
            modelo.addRow(dado);
        }
    }//GEN-LAST:event_cbMesesItemStateChanged

    private void cbMesesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMesesMouseClicked
        // TODO add your handling code here:
        folhaExtensa = new Dados().FolhasAgora(cbFolhas.getSelectedItem().toString(), new Dados().idMes(cbMeses.getSelectedItem().toString()) + "");
        modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (FolhaExtensaOBJ fe : folhaExtensa) {
            String dado[] = {fe.getFuncionario(), fe.getSalario(), fe.getIRT(), fe.getINSS(), fe.getSubsidio()};
            modelo.addRow(dado);
        }
    }//GEN-LAST:event_cbMesesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodaFolhasSalariais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodaFolhasSalariais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodaFolhasSalariais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodaFolhasSalariais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodaFolhasSalariais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoria;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbFolhas;
    private javax.swing.JComboBox<String> cbMeses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
