/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modos.Administração;

import Objetos.Dados;
import Objetos.MesesOBJ;
import Objetos.NotaDeDespesaOBJ;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quingumba
 */
public class TodasFolhasDespesas extends javax.swing.JFrame {

    /**
     * Creates new form TodasFolhasDespesas
     */
    private String previlegio2, usuario;
    private int idUsuario;
    private List<NotaDeDespesaOBJ> despesas = new ArrayList<>();
    private List<MesesOBJ> meses = new ArrayList<>();
    private int idTema;

    public int getIdTema() {
        return idTema;
    }

    public void setIdTema(int idTema) {
        this.idTema = idTema;
        String imageName = "/imagens/plano" + idTema + ".jpg";
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource(imageName)));
        if (idTema == 1) {
            lbTitulo.setForeground(new Color(0xCC00CC));
            tabela.setBackground(new Color(0x241f24));
            tabela.setForeground(new Color(0xCC00CC));
            btnLimpar.setBackground(new Color(0x241f24));
            btnAddCategoria.setBackground(new Color(0x241f24));
            btnRemover.setBackground(new Color(0x241f24));
            btnLimparLista.setBackground(new Color(0x241f24));
            txtArea.setBackground(new Color(0x241f24));
            btnVoltar.setBackground(new Color(0x241f24));
            jScrollPane1.setBackground(new Color(0x241f24));
            jScrollPane1.setForeground(new Color(0x241f24));
        }
    }

    public int getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getPrevilegio2() {
        return previlegio2;
    }

    public void setPrevilegio2(String previlegio) {
        this.previlegio2 = previlegio;
    }

    DefaultTableModel modelo;

    public TodasFolhasDespesas() {
        initComponents();

        meses = new Dados().TodosMeses();
        for (MesesOBJ Mes : meses) {
            cbMeses.addItem(Mes.getNome());
        }
        cbMeses.setSelectedIndex(new Dados().MesServidor() - 1);
        despesas = new Dados().TodasDespesasMes(Integer.toString(cbMeses.getSelectedIndex() + 1));
        modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        for (NotaDeDespesaOBJ despesa : despesas) {
            String[] dados = {despesa.getId() + "", despesa.getBeneficiario(), new Dados().getNomeDespesa(despesa.getIdDespesa()), despesa.getValor()};
            modelo.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDia = new javax.swing.JLabel();
        lbMes = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAddCategoria = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnLimparLista = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        cbMeses = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        lbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204), 2));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Mes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Ano");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 60, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("Dia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 50, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("DESCRIÇÃO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, 30));

        lbDia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDia.setForeground(new java.awt.Color(204, 0, 204));
        lbDia.setText("...");
        jPanel1.add(lbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 40, 30));

        lbMes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMes.setForeground(new java.awt.Color(204, 0, 204));
        lbMes.setText("...");
        jPanel1.add(lbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 140, 30));

        lbAno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAno.setForeground(new java.awt.Color(204, 0, 204));
        lbAno.setText("...");
        jPanel1.add(lbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Hora");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 60, 30));

        lbHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHora.setForeground(new java.awt.Color(204, 0, 204));
        lbHora.setText("...");
        jPanel1.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 90, 30));

        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel5.setOpaque(false);
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes/marca-cruzada.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, -1, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 1070, 40));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("FOLHAS DE DESPESAS REGISTRADAS");
        jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 39));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));

        tabela.setBackground(new java.awt.Color(215, 222, 230));
        tabela.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        tabela.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BENEFICIADO", "CATEGORIA", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setMinWidth(80);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabela.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 800, 250));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "ACÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCategoria.setBackground(new java.awt.Color(242, 242, 242));
        btnAddCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCategoria.setForeground(new java.awt.Color(204, 0, 204));
        btnAddCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnAddCategoria.setText("NOVA DESPESA");
        btnAddCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnAddCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAddCategoria.setIconTextGap(10);
        btnAddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 60));

        btnRemover.setBackground(new java.awt.Color(242, 242, 242));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(204, 0, 204));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/botao-apagar.png"))); // NOI18N
        btnRemover.setText("REMOVER");
        btnRemover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRemover.setIconTextGap(40);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 60));

        btnLimparLista.setBackground(new java.awt.Color(242, 242, 242));
        btnLimparLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimparLista.setForeground(new java.awt.Color(204, 0, 204));
        btnLimparLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/conta.png"))); // NOI18N
        btnLimparLista.setText("LIMPAR LISTA");
        btnLimparLista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimparLista.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimparLista.setIconTextGap(20);
        btnLimparLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparListaActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimparLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 60));

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(204, 0, 204));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/voltar.png"))); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVoltar.setIconTextGap(40);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, 60));

        cbMeses.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cbMeses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        cbMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMesesItemStateChanged(evt);
            }
        });
        jPanel3.add(cbMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 230, 480));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true), "PESQUISA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusca.setFont(new java.awt.Font("sansserif", 1, 21)); // NOI18N
        txtBusca.setForeground(new java.awt.Color(204, 204, 204));
        txtBusca.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        txtBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscaFocusLost(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });
        jPanel2.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 780, 40));

        btnLimpar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(204, 0, 204));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtro-limpo.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        btnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpar.setIconTextGap(20);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 200, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1040, 70));

        jScrollPane2.setHorizontalScrollBar(null);

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(215, 222, 230));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtArea.setForeground(new java.awt.Color(242, 0, 242));
        txtArea.setRows(5);
        txtArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        jScrollPane2.setViewportView(txtArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 800, 180));

        lbFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundasso.jpg"))); // NOI18N
        lbFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 2, true));
        lbFundo.setMaximumSize(new java.awt.Dimension(810, 690));
        lbFundo.setMinimumSize(new java.awt.Dimension(810, 690));
        lbFundo.setPreferredSize(new java.awt.Dimension(810, 690));
        jPanel1.add(lbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private int x, y;
    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnAddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoriaActionPerformed

        CaixaDespesas desp = new CaixaDespesas();
        desp.setIdUsuario(idUsuario);
        desp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddCategoriaActionPerformed

    private void btnLimparListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparListaActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        txtArea.setText("");
    }//GEN-LAST:event_btnLimparListaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMesesItemStateChanged
        // TODO add your handling code here:
        modelo = (DefaultTableModel) tabela.getModel();
        modelo.setRowCount(0);
        despesas = new Dados().TodasDespesasMes(Integer.toString(cbMeses.getSelectedIndex() + 1));
        for (NotaDeDespesaOBJ despesa : despesas) {
            String[] dados = {despesa.getId() + "", despesa.getBeneficiario(), new Dados().getNomeDespesa(despesa.getIdDespesa()), despesa.getValor()};
            modelo.addRow(dados);
        }
        lbDia.setText("...");
        lbMes.setText("...");
        lbAno.setText("...");
        lbHora.setText("...");
    }//GEN-LAST:event_cbMesesItemStateChanged

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        String texto = txtBusca.getText();
        modelo.setRowCount(0);
        despesas = new Dados().BuscaDespesas(texto);
        for (NotaDeDespesaOBJ despesa : despesas) {
            String[] dados = {despesa.getId() + "", despesa.getBeneficiario(), new Dados().getNomeDespesa(despesa.getIdDespesa()), despesa.getValor()};
            modelo.addRow(dados);
        }
        lbDia.setText("...");
        lbMes.setText("...");
        lbAno.setText("...");
        lbHora.setText("...");
    }//GEN-LAST:event_txtBuscaKeyReleased

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        int linha = tabela.getSelectedRow();
        if (linha != -1) {
            modelo = (DefaultTableModel) tabela.getModel();
            int id = Integer.parseInt(modelo.getValueAt(linha, 0).toString());
            NotaDeDespesaOBJ nota = new Dados().getDespesa(id);
            txtArea.setText(nota.getDescrição());
            lbDia.setText(nota.getDia() + "");
            lbMes.setText(new Dados().getNomeMes(nota.getMes()));
            lbAno.setText(nota.getAno() + "");
            lbHora.setText(nota.getHora());
        } else {
            lbDia.setText("...");
            lbMes.setText("...");
            lbAno.setText("...");
            lbHora.setText("...");
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtBusca.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtBuscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaFocusGained
        // TODO add your handling code here:
        txtBusca.setForeground(new Color(0xcc00cc));
        txtBusca.setText("");
    }//GEN-LAST:event_txtBuscaFocusGained

    private void txtBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscaFocusLost
        // TODO add your handling code here:
        txtBusca.setText("   Buscar saídas pelo beneficiario, data, descricao");
        txtBusca.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtBuscaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodasFolhasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodasFolhasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodasFolhasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodasFolhasDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodasFolhasDespesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategoria;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparLista;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbMeses;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbDia;
    private javax.swing.JLabel lbFundo;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbMes;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tabela;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
